# June - Copyright (c) 2022 Lucio Asnaghi, Gavin Ray
#
# Licensed and distributed under the
#   MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#
# This file may not be copied, modified, or distributed except according to those terms.

# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomImageEffectFilter of ImageEffectFilter:
    include "juce_graphics/juce_graphics.h"
    proc applyEffect(sourceImage: varref[Image], destContext: varref[Graphics], scaleFactor: cfloat, alpha: cfloat) = discard

proc newCustomImageEffectFilter*(): ptr CustomImageEffectFilter {.importcpp: "(new june::CustomImageEffectFilter)".}

proc setApplyEffectHandler*(this: var CustomImageEffectFilter, handler: proc(sourceImage: ptr Image, destContext: ptr Graphics, scaleFactor: cfloat, alpha: cfloat) {.closure.}) =
    this.onApplyEffect = bindClosure(handler)

defineCppClassInternal CustomImageFileFormat of ImageFileFormat:
    include "juce_graphics/juce_graphics.h"
    proc getFormatName(): String = discard
    proc canUnderstand(input: varref[InputStream]): bool = discard
    proc usesFileExtension(possibleFile: constptr[File]): bool = discard
    proc decodeImage(input: varref[InputStream]): Image = discard
    proc writeImageToStream(sourceImage: constptr[Image], destStream: varref[OutputStream]): bool = discard

proc newCustomImageFileFormat*(): ptr CustomImageFileFormat {.importcpp: "(new june::CustomImageFileFormat)".}

proc setGetFormatNameHandler*(this: var CustomImageFileFormat, handler: proc(): String {.closure.}) =
    this.onGetFormatName = bindClosure(handler)

proc setCanUnderstandHandler*(this: var CustomImageFileFormat, handler: proc(input: ptr InputStream): bool {.closure.}) =
    this.onCanUnderstand = bindClosure(handler)

proc setUsesFileExtensionHandler*(this: var CustomImageFileFormat, handler: proc(possibleFile: ptr File): bool {.closure.}) =
    this.onUsesFileExtension = bindClosure(handler)

proc setDecodeImageHandler*(this: var CustomImageFileFormat, handler: proc(input: ptr InputStream): Image {.closure.}) =
    this.onDecodeImage = bindClosure(handler)

proc setWriteImageToStreamHandler*(this: var CustomImageFileFormat, handler: proc(sourceImage: ptr Image, destStream: ptr OutputStream): bool {.closure.}) =
    this.onWriteImageToStream = bindClosure(handler)

defineCppClassInternal CustomImagePixelData of ImagePixelData:
    include "juce_graphics/juce_graphics.h"
    cppTypeName ImageBitmapDataReadWriteMode, "Image::BitmapData::ReadWriteMode"
    cppTypeName ImageBitmapData, "Image::BitmapData"
    proc createLowLevelContext(): UniquePtr[LowLevelGraphicsContext] = discard
    proc clone(): ReferenceCountedObjectPtr[DynamicObject] = discard
    proc createType(): UniquePtr[ImageType] {.cppconst.} = discard
    proc initialiseBitmapData(arg0: varref[ImageBitmapData], x: cint, y: cint, arg3: ImageBitmapDataReadWriteMode) = discard

proc newCustomImagePixelData*(arg0: ImagePixelFormat, width: cint, height: cint): ptr CustomImagePixelData {.importcpp: "(new june::CustomImagePixelData(@))".}

proc setCreateLowLevelContextHandler*(this: var CustomImagePixelData, handler: proc(): UniquePtr[LowLevelGraphicsContext] {.closure.}) =
    this.onCreateLowLevelContext = bindClosure(handler)

proc setCloneHandler*(this: var CustomImagePixelData, handler: proc(): ReferenceCountedObjectPtr[DynamicObject] {.closure.}) =
    this.onClone = bindClosure(handler)

proc setCreateTypeHandler*(this: var CustomImagePixelData, handler: proc(): UniquePtr[ImageType] {.closure.}) =
    this.onCreateType = bindClosure(handler)

proc setInitialiseBitmapDataHandler*(this: var CustomImagePixelData, handler: proc(arg0: ptr ImageBitmapData, x: cint, y: cint, arg3: ImageBitmapDataReadWriteMode) {.closure.}) =
    this.onInitialiseBitmapData = bindClosure(handler)

defineCppClassInternal CustomImagePixelDataBackupExtensions of ImagePixelDataBackupExtensions:
    include "juce_graphics/juce_graphics.h"
    proc setBackupEnabled(arg0: bool) = discard
    proc isBackupEnabled(): bool {.cppconst.} = discard
    proc backupNow(): bool = discard
    proc needsBackup(): bool {.cppconst.} = discard
    proc canBackup(): bool {.cppconst.} = discard

proc newCustomImagePixelDataBackupExtensions*(): ptr CustomImagePixelDataBackupExtensions {.importcpp: "(new june::CustomImagePixelDataBackupExtensions)".}

proc setSetBackupEnabledHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(arg0: bool) {.closure.}) =
    this.onSetBackupEnabled = bindClosure(handler)

proc setIsBackupEnabledHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onIsBackupEnabled = bindClosure(handler)

proc setBackupNowHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onBackupNow = bindClosure(handler)

proc setNeedsBackupHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onNeedsBackup = bindClosure(handler)

proc setCanBackupHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onCanBackup = bindClosure(handler)

defineCppClassInternal CustomImageType of ImageType:
    include "juce_graphics/juce_graphics.h"
    cppTypeName ImagePixelFormat, "Image::PixelFormat"
    proc create(arg0: ImagePixelFormat, width: cint, height: cint, shouldClearImage: bool): ReferenceCountedObjectPtr[ImagePixelData] {.cppconst.} = discard
    proc getTypeID(): cint {.cppconst.} = discard

proc newCustomImageType*(): ptr CustomImageType {.importcpp: "(new june::CustomImageType)".}

proc setCreateHandler*(this: var CustomImageType, handler: proc(arg0: ImagePixelFormat, width: cint, height: cint, shouldClearImage: bool): ReferenceCountedObjectPtr[ImagePixelData] {.closure.}) =
    this.onCreate = bindClosure(handler)

proc setGetTypeIDHandler*(this: var CustomImageType, handler: proc(): cint {.closure.}) =
    this.onGetTypeID = bindClosure(handler)

defineCppClassInternal CustomTypeface of Typeface:
    include "juce_graphics/juce_graphics.h"
    cppTypeName TypefaceNative, "Typeface::Native"
    proc createSystemFallback(text: constptr[String], language: constptr[String]): ReferenceCountedObjectPtr[Typeface] {.cppconst.} = discard
    proc getNativeDetails(): constrawptr[TypefaceNative] {.cppconst.} = discard

proc newCustomTypeface*(arg0: String, arg1: String): ptr CustomTypeface {.importcpp: "(new june::CustomTypeface(@))".}

proc setCreateSystemFallbackHandler*(this: var CustomTypeface, handler: proc(text: ptr String, language: ptr String): ReferenceCountedObjectPtr[Typeface] {.closure.}) =
    this.onCreateSystemFallback = bindClosure(handler)

proc setGetNativeDetailsHandler*(this: var CustomTypeface, handler: proc(): ptr TypefaceNative {.closure.}) =
    this.onGetNativeDetails = bindClosure(handler)

# Withheld, with the reason:
#   LowLevelGraphicsContext: const Font & returned by getFont has no Nim spelling
