# June - Copyright (c) 2022 Lucio Asnaghi, Gavin Ray
#
# Licensed and distributed under the
#   MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#
# This file may not be copied, modified, or distributed except according to those terms.

# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomCallbackMessage of CallbackMessage:
    include "juce_events/juce_events.h"
    proc messageCallback() = discard

proc newCustomCallbackMessage*(): ptr CustomCallbackMessage {.importcpp: "(new june::CustomCallbackMessage)".}

proc setMessageCallbackHandler*(this: var CustomCallbackMessage, handler: proc() {.closure.}) =
    this.onMessageCallback = bindClosure(handler)

defineCppClassInternal CustomInterprocessConnection of InterprocessConnection:
    include "juce_events/juce_events.h"
    proc connectionMade() = discard
    proc connectionLost() = discard
    proc messageReceived(message: constptr[MemoryBlock]) = discard

proc newCustomInterprocessConnection*(callbacksOnMessageThread: bool, magicMessageHeaderNumber: uint32): ptr CustomInterprocessConnection {.importcpp: "(new june::CustomInterprocessConnection(@))".}

proc setConnectionMadeHandler*(this: var CustomInterprocessConnection, handler: proc() {.closure.}) =
    this.onConnectionMade = bindClosure(handler)

proc setConnectionLostHandler*(this: var CustomInterprocessConnection, handler: proc() {.closure.}) =
    this.onConnectionLost = bindClosure(handler)

proc setMessageReceivedHandler*(this: var CustomInterprocessConnection, handler: proc(message: ptr MemoryBlock) {.closure.}) =
    this.onMessageReceived = bindClosure(handler)

defineCppClassInternal CustomInterprocessConnectionServer of InterprocessConnectionServer:
    include "juce_events/juce_events.h"
    proc createConnectionObject(): ptr InterprocessConnection = discard

proc newCustomInterprocessConnectionServer*(): ptr CustomInterprocessConnectionServer {.importcpp: "(new june::CustomInterprocessConnectionServer)".}

proc setCreateConnectionObjectHandler*(this: var CustomInterprocessConnectionServer, handler: proc(): ptr InterprocessConnection {.closure.}) =
    this.onCreateConnectionObject = bindClosure(handler)

defineCppClassInternal CustomMessageListener of MessageListener:
    include "juce_events/juce_events.h"
    proc handleMessage(message: constptr[Message]) = discard

proc newCustomMessageListener*(): ptr CustomMessageListener {.importcpp: "(new june::CustomMessageListener)".}

proc setHandleMessageHandler*(this: var CustomMessageListener, handler: proc(message: ptr Message) {.closure.}) =
    this.onHandleMessage = bindClosure(handler)

defineCppClassInternal CustomMultiTimer of MultiTimer:
    include "juce_events/juce_events.h"
    proc timerCallback(timerID: cint) = discard

proc newCustomMultiTimer*(): ptr CustomMultiTimer {.importcpp: "(new june::CustomMultiTimer)".}

proc setTimerCallbackHandler*(this: var CustomMultiTimer, handler: proc(timerID: cint) {.closure.}) =
    this.onTimerCallback = bindClosure(handler)

# Withheld, with the reason:
#   JUCEApplicationBase: const std::exception * in unhandledException has no Nim spelling
#   MountedVolumeListChangeDetector: declared only on some platforms
