# June - Copyright (c) 2022 Lucio Asnaghi, Gavin Ray
#
# Licensed and distributed under the
#   MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#
# This file may not be copied, modified, or distributed except according to those terms.

# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomImageEffectFilter of ImageEffectFilter:
    include "juce_graphics/juce_graphics.h"
    proc applyEffect(sourceImage: varref[Image], destContext: varref[Graphics], scaleFactor: cfloat, alpha: cfloat) = discard

proc newCustomImageEffectFilter*(): ptr CustomImageEffectFilter {.importcpp: "(new june::CustomImageEffectFilter)".}

proc setApplyEffectHandler*(this: var CustomImageEffectFilter, handler: proc(sourceImage: ptr Image, destContext: ptr Graphics, scaleFactor: cfloat, alpha: cfloat) {.closure.}) =
    this.onApplyEffect = bindClosure(handler)

defineCppClassInternal CustomImageFileFormat of ImageFileFormat:
    include "juce_graphics/juce_graphics.h"
    proc getFormatName(): String = discard
    proc canUnderstand(input: varref[InputStream]): bool = discard
    proc usesFileExtension(possibleFile: constptr[File]): bool = discard
    proc decodeImage(input: varref[InputStream]): Image = discard
    proc writeImageToStream(sourceImage: constptr[Image], destStream: varref[OutputStream]): bool = discard

proc newCustomImageFileFormat*(): ptr CustomImageFileFormat {.importcpp: "(new june::CustomImageFileFormat)".}

proc setGetFormatNameHandler*(this: var CustomImageFileFormat, handler: proc(): String {.closure.}) =
    this.onGetFormatName = bindClosure(handler)

proc setCanUnderstandHandler*(this: var CustomImageFileFormat, handler: proc(input: ptr InputStream): bool {.closure.}) =
    this.onCanUnderstand = bindClosure(handler)

proc setUsesFileExtensionHandler*(this: var CustomImageFileFormat, handler: proc(possibleFile: ptr File): bool {.closure.}) =
    this.onUsesFileExtension = bindClosure(handler)

proc setDecodeImageHandler*(this: var CustomImageFileFormat, handler: proc(input: ptr InputStream): Image {.closure.}) =
    this.onDecodeImage = bindClosure(handler)

proc setWriteImageToStreamHandler*(this: var CustomImageFileFormat, handler: proc(sourceImage: ptr Image, destStream: ptr OutputStream): bool {.closure.}) =
    this.onWriteImageToStream = bindClosure(handler)

defineCppClassInternal CustomImagePixelDataBackupExtensions of ImagePixelDataBackupExtensions:
    include "juce_graphics/juce_graphics.h"
    proc setBackupEnabled(arg0: bool) = discard
    proc isBackupEnabled(): bool {.cppconst.} = discard
    proc backupNow(): bool = discard
    proc needsBackup(): bool {.cppconst.} = discard
    proc canBackup(): bool {.cppconst.} = discard

proc newCustomImagePixelDataBackupExtensions*(): ptr CustomImagePixelDataBackupExtensions {.importcpp: "(new june::CustomImagePixelDataBackupExtensions)".}

proc setSetBackupEnabledHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(arg0: bool) {.closure.}) =
    this.onSetBackupEnabled = bindClosure(handler)

proc setIsBackupEnabledHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onIsBackupEnabled = bindClosure(handler)

proc setBackupNowHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onBackupNow = bindClosure(handler)

proc setNeedsBackupHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onNeedsBackup = bindClosure(handler)

proc setCanBackupHandler*(this: var CustomImagePixelDataBackupExtensions, handler: proc(): bool {.closure.}) =
    this.onCanBackup = bindClosure(handler)

# Withheld, with the reason:
#   ImagePixelData: Ptr returned by clone has no Nim spelling
#   ImageType: ImagePixelData::Ptr returned by create has no Nim spelling
#   LowLevelGraphicsContext: const Rectangle<int> & in clipToRectangle has no Nim spelling
#   Typeface: Typeface::Ptr returned by createSystemFallback has no Nim spelling
