# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomUndoableAction of UndoableAction:
    include "juce_data_structures/juce_data_structures.h"
    proc perform(): bool = discard
    proc undo(): bool = discard

proc newCustomUndoableAction*(): ptr CustomUndoableAction {.importcpp: "(new june::CustomUndoableAction)".}

proc setPerformHandler*(this: var CustomUndoableAction, handler: proc(): bool {.closure.}) =
    this.onPerform = bindClosure(handler)

proc setUndoHandler*(this: var CustomUndoableAction, handler: proc(): bool {.closure.}) =
    this.onUndo = bindClosure(handler)

# Withheld, with the reason:
#   ValueTreeSynchroniser: const void * in stateChanged has no Nim spelling
