# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomCallbackMessage of CallbackMessage:
    include "juce_events/juce_events.h"
    proc messageCallback() = discard

proc newCustomCallbackMessage*(): ptr CustomCallbackMessage {.importcpp: "(new june::CustomCallbackMessage)".}

proc setMessageCallbackHandler*(this: var CustomCallbackMessage, handler: proc() {.closure.}) =
    this.onMessageCallback = bindClosure(handler)

defineCppClassInternal CustomInterprocessConnection of InterprocessConnection:
    include "juce_events/juce_events.h"
    proc connectionMade() = discard
    proc connectionLost() = discard
    proc messageReceived(message: constptr[MemoryBlock]) = discard

proc newCustomInterprocessConnection*(callbacksOnMessageThread: bool, magicMessageHeaderNumber: uint32): ptr CustomInterprocessConnection {.importcpp: "(new june::CustomInterprocessConnection(@))".}

proc setConnectionMadeHandler*(this: var CustomInterprocessConnection, handler: proc() {.closure.}) =
    this.onConnectionMade = bindClosure(handler)

proc setConnectionLostHandler*(this: var CustomInterprocessConnection, handler: proc() {.closure.}) =
    this.onConnectionLost = bindClosure(handler)

proc setMessageReceivedHandler*(this: var CustomInterprocessConnection, handler: proc(message: ptr MemoryBlock) {.closure.}) =
    this.onMessageReceived = bindClosure(handler)

defineCppClassInternal CustomInterprocessConnectionServer of InterprocessConnectionServer:
    include "juce_events/juce_events.h"
    proc createConnectionObject(): ptr InterprocessConnection = discard

proc newCustomInterprocessConnectionServer*(): ptr CustomInterprocessConnectionServer {.importcpp: "(new june::CustomInterprocessConnectionServer)".}

proc setCreateConnectionObjectHandler*(this: var CustomInterprocessConnectionServer, handler: proc(): ptr InterprocessConnection {.closure.}) =
    this.onCreateConnectionObject = bindClosure(handler)

defineCppClassInternal CustomJUCEApplicationBase of JUCEApplicationBase:
    include "juce_events/juce_events.h"
    cppTypeName CppException, "std::exception"
    proc getApplicationName(): constval[String] = discard
    proc getApplicationVersion(): constval[String] = discard
    proc moreThanOneInstanceAllowed(): bool = discard
    proc initialise(commandLineParameters: constptr[String]) = discard
    proc shutdown() = discard
    proc anotherInstanceStarted(commandLine: constptr[String]) = discard
    proc systemRequestedQuit() = discard
    proc suspended() = discard
    proc resumed() = discard
    proc unhandledException(arg0: constrawptr[CppException], sourceFilename: constptr[String], lineNumber: cint) = discard

proc newCustomJUCEApplicationBase*(): ptr CustomJUCEApplicationBase {.importcpp: "(new june::CustomJUCEApplicationBase)".}

proc setGetApplicationNameHandler*(this: var CustomJUCEApplicationBase, handler: proc(): String {.closure.}) =
    this.onGetApplicationName = bindClosure(handler)

proc setGetApplicationVersionHandler*(this: var CustomJUCEApplicationBase, handler: proc(): String {.closure.}) =
    this.onGetApplicationVersion = bindClosure(handler)

proc setMoreThanOneInstanceAllowedHandler*(this: var CustomJUCEApplicationBase, handler: proc(): bool {.closure.}) =
    this.onMoreThanOneInstanceAllowed = bindClosure(handler)

proc setInitialiseHandler*(this: var CustomJUCEApplicationBase, handler: proc(commandLineParameters: ptr String) {.closure.}) =
    this.onInitialise = bindClosure(handler)

proc setShutdownHandler*(this: var CustomJUCEApplicationBase, handler: proc() {.closure.}) =
    this.onShutdown = bindClosure(handler)

proc setAnotherInstanceStartedHandler*(this: var CustomJUCEApplicationBase, handler: proc(commandLine: ptr String) {.closure.}) =
    this.onAnotherInstanceStarted = bindClosure(handler)

proc setSystemRequestedQuitHandler*(this: var CustomJUCEApplicationBase, handler: proc() {.closure.}) =
    this.onSystemRequestedQuit = bindClosure(handler)

proc setSuspendedHandler*(this: var CustomJUCEApplicationBase, handler: proc() {.closure.}) =
    this.onSuspended = bindClosure(handler)

proc setResumedHandler*(this: var CustomJUCEApplicationBase, handler: proc() {.closure.}) =
    this.onResumed = bindClosure(handler)

proc setUnhandledExceptionHandler*(this: var CustomJUCEApplicationBase, handler: proc(arg0: ptr CppException, sourceFilename: ptr String, lineNumber: cint) {.closure.}) =
    this.onUnhandledException = bindClosure(handler)

defineCppClassInternal CustomMessageListener of MessageListener:
    include "juce_events/juce_events.h"
    proc handleMessage(message: constptr[Message]) = discard

proc newCustomMessageListener*(): ptr CustomMessageListener {.importcpp: "(new june::CustomMessageListener)".}

proc setHandleMessageHandler*(this: var CustomMessageListener, handler: proc(message: ptr Message) {.closure.}) =
    this.onHandleMessage = bindClosure(handler)

defineCppClassInternal CustomMessageManagerMessageBase of MessageManagerMessageBase:
    include "juce_events/juce_events.h"
    cppParent "juce::MessageManager::MessageBase"
    proc messageCallback() = discard

proc newCustomMessageManagerMessageBase*(): ptr CustomMessageManagerMessageBase {.importcpp: "(new june::CustomMessageManagerMessageBase)".}

proc setMessageCallbackHandler*(this: var CustomMessageManagerMessageBase, handler: proc() {.closure.}) =
    this.onMessageCallback = bindClosure(handler)

defineCppClassInternal CustomMultiTimer of MultiTimer:
    include "juce_events/juce_events.h"
    proc timerCallback(timerID: cint) = discard

proc newCustomMultiTimer*(): ptr CustomMultiTimer {.importcpp: "(new june::CustomMultiTimer)".}

proc setTimerCallbackHandler*(this: var CustomMultiTimer, handler: proc(timerID: cint) {.closure.}) =
    this.onTimerCallback = bindClosure(handler)

# Withheld, with the reason:
#   MountedVolumeListChangeDetector: declared only on some platforms
