# June - Copyright (c) 2022 Lucio Asnaghi, Gavin Ray
#
# Licensed and distributed under the
#   MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#
# This file may not be copied, modified, or distributed except according to those terms.

# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomAccessibilityNumericValueInterface of AccessibilityNumericValueInterface:
    include "juce_gui_basics/juce_gui_basics.h"
    proc isReadOnly(): bool {.cppconst.} = discard
    proc getCurrentValue(): cdouble {.cppconst.} = discard
    proc setValue(newValue: cdouble) = discard

proc newCustomAccessibilityNumericValueInterface*(): ptr CustomAccessibilityNumericValueInterface {.importcpp: "(new june::CustomAccessibilityNumericValueInterface)".}

proc setIsReadOnlyHandler*(this: var CustomAccessibilityNumericValueInterface, handler: proc(): bool {.closure.}) =
    this.onIsReadOnly = bindClosure(handler)

proc setGetCurrentValueHandler*(this: var CustomAccessibilityNumericValueInterface, handler: proc(): cdouble {.closure.}) =
    this.onGetCurrentValue = bindClosure(handler)

proc setSetValueHandler*(this: var CustomAccessibilityNumericValueInterface, handler: proc(newValue: cdouble) {.closure.}) =
    this.onSetValue = bindClosure(handler)

defineCppClassInternal CustomAccessibilityRangedNumericValueInterface of AccessibilityRangedNumericValueInterface:
    include "juce_gui_basics/juce_gui_basics.h"
    cppTypeName AccessibilityValueInterfaceAccessibleValueRange, "AccessibilityValueInterface::AccessibleValueRange"
    proc isReadOnly(): bool {.cppconst.} = discard
    proc getCurrentValue(): cdouble {.cppconst.} = discard
    proc setValue(newValue: cdouble) = discard
    proc getRange(): AccessibilityValueInterfaceAccessibleValueRange {.cppconst.} = discard

proc newCustomAccessibilityRangedNumericValueInterface*(): ptr CustomAccessibilityRangedNumericValueInterface {.importcpp: "(new june::CustomAccessibilityRangedNumericValueInterface)".}

proc setIsReadOnlyHandler*(this: var CustomAccessibilityRangedNumericValueInterface, handler: proc(): bool {.closure.}) =
    this.onIsReadOnly = bindClosure(handler)

proc setGetCurrentValueHandler*(this: var CustomAccessibilityRangedNumericValueInterface, handler: proc(): cdouble {.closure.}) =
    this.onGetCurrentValue = bindClosure(handler)

proc setSetValueHandler*(this: var CustomAccessibilityRangedNumericValueInterface, handler: proc(newValue: cdouble) {.closure.}) =
    this.onSetValue = bindClosure(handler)

proc setGetRangeHandler*(this: var CustomAccessibilityRangedNumericValueInterface, handler: proc(): AccessibilityValueInterfaceAccessibleValueRange {.closure.}) =
    this.onGetRange = bindClosure(handler)

defineCppClassInternal CustomAccessibilityTextInterface of AccessibilityTextInterface:
    include "juce_gui_basics/juce_gui_basics.h"
    proc isDisplayingProtectedText(): bool {.cppconst.} = discard
    proc isReadOnly(): bool {.cppconst.} = discard
    proc getTotalNumCharacters(): cint {.cppconst.} = discard
    proc getSelection(): Range[cint] {.cppconst.} = discard
    proc setSelection(newRange: Range[cint]) = discard
    proc getTextInsertionOffset(): cint {.cppconst.} = discard
    proc getText(range: Range[cint]): String {.cppconst.} = discard
    proc setText(newText: constptr[String]) = discard
    proc getTextBounds(textRange: Range[cint]): RectangleList[cint] {.cppconst.} = discard
    proc getOffsetAtPoint(point: Point[cint]): cint {.cppconst.} = discard

proc newCustomAccessibilityTextInterface*(): ptr CustomAccessibilityTextInterface {.importcpp: "(new june::CustomAccessibilityTextInterface)".}

proc setIsDisplayingProtectedTextHandler*(this: var CustomAccessibilityTextInterface, handler: proc(): bool {.closure.}) =
    this.onIsDisplayingProtectedText = bindClosure(handler)

proc setIsReadOnlyHandler*(this: var CustomAccessibilityTextInterface, handler: proc(): bool {.closure.}) =
    this.onIsReadOnly = bindClosure(handler)

proc setGetTotalNumCharactersHandler*(this: var CustomAccessibilityTextInterface, handler: proc(): cint {.closure.}) =
    this.onGetTotalNumCharacters = bindClosure(handler)

proc setGetSelectionHandler*(this: var CustomAccessibilityTextInterface, handler: proc(): Range[cint] {.closure.}) =
    this.onGetSelection = bindClosure(handler)

proc setSetSelectionHandler*(this: var CustomAccessibilityTextInterface, handler: proc(newRange: Range[cint]) {.closure.}) =
    this.onSetSelection = bindClosure(handler)

proc setGetTextInsertionOffsetHandler*(this: var CustomAccessibilityTextInterface, handler: proc(): cint {.closure.}) =
    this.onGetTextInsertionOffset = bindClosure(handler)

proc setGetTextHandler*(this: var CustomAccessibilityTextInterface, handler: proc(range: Range[cint]): String {.closure.}) =
    this.onGetText = bindClosure(handler)

proc setSetTextHandler*(this: var CustomAccessibilityTextInterface, handler: proc(newText: ptr String) {.closure.}) =
    this.onSetText = bindClosure(handler)

proc setGetTextBoundsHandler*(this: var CustomAccessibilityTextInterface, handler: proc(textRange: Range[cint]): RectangleList[cint] {.closure.}) =
    this.onGetTextBounds = bindClosure(handler)

proc setGetOffsetAtPointHandler*(this: var CustomAccessibilityTextInterface, handler: proc(point: Point[cint]): cint {.closure.}) =
    this.onGetOffsetAtPoint = bindClosure(handler)

defineCppClassInternal CustomAccessibilityTextValueInterface of AccessibilityTextValueInterface:
    include "juce_gui_basics/juce_gui_basics.h"
    proc isReadOnly(): bool {.cppconst.} = discard
    proc getCurrentValueAsString(): String {.cppconst.} = discard
    proc setValueAsString(newValue: constptr[String]) = discard

proc newCustomAccessibilityTextValueInterface*(): ptr CustomAccessibilityTextValueInterface {.importcpp: "(new june::CustomAccessibilityTextValueInterface)".}

proc setIsReadOnlyHandler*(this: var CustomAccessibilityTextValueInterface, handler: proc(): bool {.closure.}) =
    this.onIsReadOnly = bindClosure(handler)

proc setGetCurrentValueAsStringHandler*(this: var CustomAccessibilityTextValueInterface, handler: proc(): String {.closure.}) =
    this.onGetCurrentValueAsString = bindClosure(handler)

proc setSetValueAsStringHandler*(this: var CustomAccessibilityTextValueInterface, handler: proc(newValue: ptr String) {.closure.}) =
    this.onSetValueAsString = bindClosure(handler)

defineCppClassInternal CustomAccessibilityValueInterface of AccessibilityValueInterface:
    include "juce_gui_basics/juce_gui_basics.h"
    cppTypeName AccessibilityValueInterfaceAccessibleValueRange, "AccessibilityValueInterface::AccessibleValueRange"
    proc isReadOnly(): bool {.cppconst.} = discard
    proc getCurrentValue(): cdouble {.cppconst.} = discard
    proc getCurrentValueAsString(): String {.cppconst.} = discard
    proc setValue(newValue: cdouble) = discard
    proc setValueAsString(newValue: constptr[String]) = discard
    proc getRange(): AccessibilityValueInterfaceAccessibleValueRange {.cppconst.} = discard

proc newCustomAccessibilityValueInterface*(): ptr CustomAccessibilityValueInterface {.importcpp: "(new june::CustomAccessibilityValueInterface)".}

proc setIsReadOnlyHandler*(this: var CustomAccessibilityValueInterface, handler: proc(): bool {.closure.}) =
    this.onIsReadOnly = bindClosure(handler)

proc setGetCurrentValueHandler*(this: var CustomAccessibilityValueInterface, handler: proc(): cdouble {.closure.}) =
    this.onGetCurrentValue = bindClosure(handler)

proc setGetCurrentValueAsStringHandler*(this: var CustomAccessibilityValueInterface, handler: proc(): String {.closure.}) =
    this.onGetCurrentValueAsString = bindClosure(handler)

proc setSetValueHandler*(this: var CustomAccessibilityValueInterface, handler: proc(newValue: cdouble) {.closure.}) =
    this.onSetValue = bindClosure(handler)

proc setSetValueAsStringHandler*(this: var CustomAccessibilityValueInterface, handler: proc(newValue: ptr String) {.closure.}) =
    this.onSetValueAsString = bindClosure(handler)

proc setGetRangeHandler*(this: var CustomAccessibilityValueInterface, handler: proc(): AccessibilityValueInterfaceAccessibleValueRange {.closure.}) =
    this.onGetRange = bindClosure(handler)

defineCppClassInternal CustomApplicationCommandManagerListener of ApplicationCommandManagerListener:
    include "juce_gui_basics/juce_gui_basics.h"
    cppTypeName ApplicationCommandTargetInvocationInfo, "ApplicationCommandTarget::InvocationInfo"
    proc applicationCommandInvoked(arg0: constptr[ApplicationCommandTargetInvocationInfo]) = discard
    proc applicationCommandListChanged() = discard

proc newCustomApplicationCommandManagerListener*(): ptr CustomApplicationCommandManagerListener {.importcpp: "(new june::CustomApplicationCommandManagerListener)".}

proc setApplicationCommandInvokedHandler*(this: var CustomApplicationCommandManagerListener, handler: proc(arg0: ptr ApplicationCommandTargetInvocationInfo) {.closure.}) =
    this.onApplicationCommandInvoked = bindClosure(handler)

proc setApplicationCommandListChangedHandler*(this: var CustomApplicationCommandManagerListener, handler: proc() {.closure.}) =
    this.onApplicationCommandListChanged = bindClosure(handler)

defineCppClassInternal CustomBorderedComponentBoundsConstrainer of BorderedComponentBoundsConstrainer:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getWrappedConstrainer(): ptr ComponentBoundsConstrainer {.cppconst.} = discard
    proc getAdditionalBorder(): BorderSize[cint] {.cppconst.} = discard

proc newCustomBorderedComponentBoundsConstrainer*(): ptr CustomBorderedComponentBoundsConstrainer {.importcpp: "(new june::CustomBorderedComponentBoundsConstrainer)".}

proc setGetWrappedConstrainerHandler*(this: var CustomBorderedComponentBoundsConstrainer, handler: proc(): ptr ComponentBoundsConstrainer {.closure.}) =
    this.onGetWrappedConstrainer = bindClosure(handler)

proc setGetAdditionalBorderHandler*(this: var CustomBorderedComponentBoundsConstrainer, handler: proc(): BorderSize[cint] {.closure.}) =
    this.onGetAdditionalBorder = bindClosure(handler)

defineCppClassInternal CustomBubbleComponent of BubbleComponent:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getContentSize(width: varref[cint], height: varref[cint]) = discard
    proc paintContent(g: varref[Graphics], width: cint, height: cint) = discard

proc newCustomBubbleComponent*(): ptr CustomBubbleComponent {.importcpp: "(new june::CustomBubbleComponent)".}

proc setGetContentSizeHandler*(this: var CustomBubbleComponent, handler: proc(width: ptr cint, height: ptr cint) {.closure.}) =
    this.onGetContentSize = bindClosure(handler)

proc setPaintContentHandler*(this: var CustomBubbleComponent, handler: proc(g: ptr Graphics, width: cint, height: cint) {.closure.}) =
    this.onPaintContent = bindClosure(handler)

defineCppClassInternal CustomButtonPropertyComponent of ButtonPropertyComponent:
    include "juce_gui_basics/juce_gui_basics.h"
    proc buttonClicked() = discard
    proc getButtonText(): String {.cppconst.} = discard

proc newCustomButtonPropertyComponent*(propertyName: String, triggerOnMouseDown: bool): ptr CustomButtonPropertyComponent {.importcpp: "(new june::CustomButtonPropertyComponent(@))".}

proc setButtonClickedHandler*(this: var CustomButtonPropertyComponent, handler: proc() {.closure.}) =
    this.onButtonClicked = bindClosure(handler)

proc setGetButtonTextHandler*(this: var CustomButtonPropertyComponent, handler: proc(): String {.closure.}) =
    this.onGetButtonText = bindClosure(handler)

defineCppClassInternal CustomCachedComponentImage of CachedComponentImage:
    include "juce_gui_basics/juce_gui_basics.h"
    proc paint(arg0: varref[Graphics]) = discard
    proc invalidateAll(): bool = discard
    proc invalidate(area: constptr[Rectangle[cint]]): bool = discard
    proc releaseResources() = discard

proc newCustomCachedComponentImage*(): ptr CustomCachedComponentImage {.importcpp: "(new june::CustomCachedComponentImage)".}

proc setPaintHandler*(this: var CustomCachedComponentImage, handler: proc(arg0: ptr Graphics) {.closure.}) =
    this.onPaint = bindClosure(handler)

proc setInvalidateAllHandler*(this: var CustomCachedComponentImage, handler: proc(): bool {.closure.}) =
    this.onInvalidateAll = bindClosure(handler)

proc setInvalidateHandler*(this: var CustomCachedComponentImage, handler: proc(area: ptr Rectangle[cint]): bool {.closure.}) =
    this.onInvalidate = bindClosure(handler)

proc setReleaseResourcesHandler*(this: var CustomCachedComponentImage, handler: proc() {.closure.}) =
    this.onReleaseResources = bindClosure(handler)

defineCppClassInternal CustomComponentMovementWatcher of ComponentMovementWatcher:
    include "juce_gui_basics/juce_gui_basics.h"
    proc componentMovedOrResized(wasMoved: bool, wasResized: bool) = discard
    proc componentPeerChanged() = discard
    proc componentVisibilityChanged() = discard

proc newCustomComponentMovementWatcher*(componentToWatch: ptr Component): ptr CustomComponentMovementWatcher {.importcpp: "(new june::CustomComponentMovementWatcher(@))".}

proc setComponentMovedOrResizedHandler*(this: var CustomComponentMovementWatcher, handler: proc(wasMoved: bool, wasResized: bool) {.closure.}) =
    this.onComponentMovedOrResized = bindClosure(handler)

proc setComponentPeerChangedHandler*(this: var CustomComponentMovementWatcher, handler: proc() {.closure.}) =
    this.onComponentPeerChanged = bindClosure(handler)

proc setComponentVisibilityChangedHandler*(this: var CustomComponentMovementWatcher, handler: proc() {.closure.}) =
    this.onComponentVisibilityChanged = bindClosure(handler)

defineCppClassInternal CustomDarkModeSettingListener of DarkModeSettingListener:
    include "juce_gui_basics/juce_gui_basics.h"
    proc darkModeSettingChanged() = discard

proc newCustomDarkModeSettingListener*(): ptr CustomDarkModeSettingListener {.importcpp: "(new june::CustomDarkModeSettingListener)".}

proc setDarkModeSettingChangedHandler*(this: var CustomDarkModeSettingListener, handler: proc() {.closure.}) =
    this.onDarkModeSettingChanged = bindClosure(handler)

defineCppClassInternal CustomDirectoryContentsDisplayComponent of DirectoryContentsDisplayComponent:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getNumSelectedFiles(): cint {.cppconst.} = discard
    proc getSelectedFile(index: cint): File {.cppconst.} = discard
    proc deselectAllFiles() = discard
    proc scrollToTop() = discard
    proc setSelectedFile(arg0: constptr[File]) = discard

proc newCustomDirectoryContentsDisplayComponent*(listToShow: DirectoryContentsList): ptr CustomDirectoryContentsDisplayComponent {.importcpp: "(new june::CustomDirectoryContentsDisplayComponent(@))".}

proc setGetNumSelectedFilesHandler*(this: var CustomDirectoryContentsDisplayComponent, handler: proc(): cint {.closure.}) =
    this.onGetNumSelectedFiles = bindClosure(handler)

proc setGetSelectedFileHandler*(this: var CustomDirectoryContentsDisplayComponent, handler: proc(index: cint): File {.closure.}) =
    this.onGetSelectedFile = bindClosure(handler)

proc setDeselectAllFilesHandler*(this: var CustomDirectoryContentsDisplayComponent, handler: proc() {.closure.}) =
    this.onDeselectAllFiles = bindClosure(handler)

proc setScrollToTopHandler*(this: var CustomDirectoryContentsDisplayComponent, handler: proc() {.closure.}) =
    this.onScrollToTop = bindClosure(handler)

proc setSetSelectedFileHandler*(this: var CustomDirectoryContentsDisplayComponent, handler: proc(arg0: ptr File) {.closure.}) =
    this.onSetSelectedFile = bindClosure(handler)

defineCppClassInternal CustomDragAndDropTarget of DragAndDropTarget:
    include "juce_gui_basics/juce_gui_basics.h"
    cppTypeName DragAndDropTargetSourceDetails, "DragAndDropTarget::SourceDetails"
    proc isInterestedInDragSource(dragSourceDetails: constptr[DragAndDropTargetSourceDetails]): bool = discard
    proc itemDropped(dragSourceDetails: constptr[DragAndDropTargetSourceDetails]) = discard

proc newCustomDragAndDropTarget*(): ptr CustomDragAndDropTarget {.importcpp: "(new june::CustomDragAndDropTarget)".}

proc setIsInterestedInDragSourceHandler*(this: var CustomDragAndDropTarget, handler: proc(dragSourceDetails: ptr DragAndDropTargetSourceDetails): bool {.closure.}) =
    this.onIsInterestedInDragSource = bindClosure(handler)

proc setItemDroppedHandler*(this: var CustomDragAndDropTarget, handler: proc(dragSourceDetails: ptr DragAndDropTargetSourceDetails) {.closure.}) =
    this.onItemDropped = bindClosure(handler)

defineCppClassInternal CustomDrawable of Drawable:
    include "juce_gui_basics/juce_gui_basics.h"
    proc createCopy(): UniquePtr[Drawable] {.cppconst.} = discard
    proc getOutlineAsPath(): Path {.cppconst.} = discard
    proc getDrawableBounds(): Rectangle[cfloat] {.cppconst.} = discard

proc newCustomDrawable*(): ptr CustomDrawable {.importcpp: "(new june::CustomDrawable)".}

proc setCreateCopyHandler*(this: var CustomDrawable, handler: proc(): UniquePtr[Drawable] {.closure.}) =
    this.onCreateCopy = bindClosure(handler)

proc setGetOutlineAsPathHandler*(this: var CustomDrawable, handler: proc(): Path {.closure.}) =
    this.onGetOutlineAsPath = bindClosure(handler)

proc setGetDrawableBoundsHandler*(this: var CustomDrawable, handler: proc(): Rectangle[cfloat] {.closure.}) =
    this.onGetDrawableBounds = bindClosure(handler)

defineCppClassInternal CustomFileBrowserListener of FileBrowserListener:
    include "juce_gui_basics/juce_gui_basics.h"
    proc selectionChanged() = discard
    proc fileClicked(file: constptr[File], e: constptr[MouseEvent]) = discard
    proc fileDoubleClicked(file: constptr[File]) = discard
    proc browserRootChanged(newRoot: constptr[File]) = discard

proc newCustomFileBrowserListener*(): ptr CustomFileBrowserListener {.importcpp: "(new june::CustomFileBrowserListener)".}

proc setSelectionChangedHandler*(this: var CustomFileBrowserListener, handler: proc() {.closure.}) =
    this.onSelectionChanged = bindClosure(handler)

proc setFileClickedHandler*(this: var CustomFileBrowserListener, handler: proc(file: ptr File, e: ptr MouseEvent) {.closure.}) =
    this.onFileClicked = bindClosure(handler)

proc setFileDoubleClickedHandler*(this: var CustomFileBrowserListener, handler: proc(file: ptr File) {.closure.}) =
    this.onFileDoubleClicked = bindClosure(handler)

proc setBrowserRootChangedHandler*(this: var CustomFileBrowserListener, handler: proc(newRoot: ptr File) {.closure.}) =
    this.onBrowserRootChanged = bindClosure(handler)

defineCppClassInternal CustomFileDragAndDropTarget of FileDragAndDropTarget:
    include "juce_gui_basics/juce_gui_basics.h"
    proc isInterestedInFileDrag(files: constptr[StringArray]): bool = discard
    proc filesDropped(files: constptr[StringArray], x: cint, y: cint) = discard

proc newCustomFileDragAndDropTarget*(): ptr CustomFileDragAndDropTarget {.importcpp: "(new june::CustomFileDragAndDropTarget)".}

proc setIsInterestedInFileDragHandler*(this: var CustomFileDragAndDropTarget, handler: proc(files: ptr StringArray): bool {.closure.}) =
    this.onIsInterestedInFileDrag = bindClosure(handler)

proc setFilesDroppedHandler*(this: var CustomFileDragAndDropTarget, handler: proc(files: ptr StringArray, x: cint, y: cint) {.closure.}) =
    this.onFilesDropped = bindClosure(handler)

defineCppClassInternal CustomFilePreviewComponent of FilePreviewComponent:
    include "juce_gui_basics/juce_gui_basics.h"
    proc selectedFileChanged(newSelectedFile: constptr[File]) = discard

proc newCustomFilePreviewComponent*(): ptr CustomFilePreviewComponent {.importcpp: "(new june::CustomFilePreviewComponent)".}

proc setSelectedFileChangedHandler*(this: var CustomFilePreviewComponent, handler: proc(newSelectedFile: ptr File) {.closure.}) =
    this.onSelectedFileChanged = bindClosure(handler)

defineCppClassInternal CustomFilenameComponentListener of FilenameComponentListener:
    include "juce_gui_basics/juce_gui_basics.h"
    proc filenameComponentChanged(fileComponentThatHasChanged: ptr FilenameComponent) = discard

proc newCustomFilenameComponentListener*(): ptr CustomFilenameComponentListener {.importcpp: "(new june::CustomFilenameComponentListener)".}

proc setFilenameComponentChangedHandler*(this: var CustomFilenameComponentListener, handler: proc(fileComponentThatHasChanged: ptr FilenameComponent) {.closure.}) =
    this.onFilenameComponentChanged = bindClosure(handler)

defineCppClassInternal CustomFocusChangeListener of FocusChangeListener:
    include "juce_gui_basics/juce_gui_basics.h"
    proc globalFocusChanged(focusedComponent: ptr Component) = discard

proc newCustomFocusChangeListener*(): ptr CustomFocusChangeListener {.importcpp: "(new june::CustomFocusChangeListener)".}

proc setGlobalFocusChangedHandler*(this: var CustomFocusChangeListener, handler: proc(focusedComponent: ptr Component) {.closure.}) =
    this.onGlobalFocusChanged = bindClosure(handler)

defineCppClassInternal CustomKeyListener of KeyListener:
    include "juce_gui_basics/juce_gui_basics.h"
    proc keyPressed(key: constptr[KeyPress], originatingComponent: ptr Component): bool = discard

proc newCustomKeyListener*(): ptr CustomKeyListener {.importcpp: "(new june::CustomKeyListener)".}

proc setKeyPressedHandler*(this: var CustomKeyListener, handler: proc(key: ptr KeyPress, originatingComponent: ptr Component): bool {.closure.}) =
    this.onKeyPressed = bindClosure(handler)

defineCppClassInternal CustomMenuBarModel of MenuBarModel:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getMenuBarNames(): StringArray = discard
    proc getMenuForIndex(topLevelMenuIndex: cint, menuName: constptr[String]): PopupMenu = discard
    proc menuItemSelected(menuItemID: cint, topLevelMenuIndex: cint) = discard

proc newCustomMenuBarModel*(): ptr CustomMenuBarModel {.importcpp: "(new june::CustomMenuBarModel)".}

proc setGetMenuBarNamesHandler*(this: var CustomMenuBarModel, handler: proc(): StringArray {.closure.}) =
    this.onGetMenuBarNames = bindClosure(handler)

proc setGetMenuForIndexHandler*(this: var CustomMenuBarModel, handler: proc(topLevelMenuIndex: cint, menuName: ptr String): PopupMenu {.closure.}) =
    this.onGetMenuForIndex = bindClosure(handler)

proc setMenuItemSelectedHandler*(this: var CustomMenuBarModel, handler: proc(menuItemID: cint, topLevelMenuIndex: cint) {.closure.}) =
    this.onMenuItemSelected = bindClosure(handler)

defineCppClassInternal CustomPropertyComponent of PropertyComponent:
    include "juce_gui_basics/juce_gui_basics.h"
    proc refresh() = discard

proc newCustomPropertyComponent*(propertyName: String, preferredHeight: cint): ptr CustomPropertyComponent {.importcpp: "(new june::CustomPropertyComponent(@))".}

proc setRefreshHandler*(this: var CustomPropertyComponent, handler: proc() {.closure.}) =
    this.onRefresh = bindClosure(handler)

defineCppClassInternal CustomRelativeCoordinatePositionerBase of RelativeCoordinatePositionerBase:
    include "juce_gui_basics/juce_gui_basics.h"
    proc registerCoordinates(): bool = discard
    proc applyToComponentBounds() = discard

proc newCustomRelativeCoordinatePositionerBase*(arg0: Component): ptr CustomRelativeCoordinatePositionerBase {.importcpp: "(new june::CustomRelativeCoordinatePositionerBase(@))".}

proc setRegisterCoordinatesHandler*(this: var CustomRelativeCoordinatePositionerBase, handler: proc(): bool {.closure.}) =
    this.onRegisterCoordinates = bindClosure(handler)

proc setApplyToComponentBoundsHandler*(this: var CustomRelativeCoordinatePositionerBase, handler: proc() {.closure.}) =
    this.onApplyToComponentBounds = bindClosure(handler)

defineCppClassInternal CustomTableListBoxModel of TableListBoxModel:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getNumRows(): cint = discard
    proc paintRowBackground(arg0: varref[Graphics], rowNumber: cint, width: cint, height: cint, rowIsSelected: bool) = discard
    proc paintCell(arg0: varref[Graphics], rowNumber: cint, columnId: cint, width: cint, height: cint, rowIsSelected: bool) = discard

proc newCustomTableListBoxModel*(): ptr CustomTableListBoxModel {.importcpp: "(new june::CustomTableListBoxModel)".}

proc setGetNumRowsHandler*(this: var CustomTableListBoxModel, handler: proc(): cint {.closure.}) =
    this.onGetNumRows = bindClosure(handler)

proc setPaintRowBackgroundHandler*(this: var CustomTableListBoxModel, handler: proc(arg0: ptr Graphics, rowNumber: cint, width: cint, height: cint, rowIsSelected: bool) {.closure.}) =
    this.onPaintRowBackground = bindClosure(handler)

proc setPaintCellHandler*(this: var CustomTableListBoxModel, handler: proc(arg0: ptr Graphics, rowNumber: cint, columnId: cint, width: cint, height: cint, rowIsSelected: bool) {.closure.}) =
    this.onPaintCell = bindClosure(handler)

defineCppClassInternal CustomTextDragAndDropTarget of TextDragAndDropTarget:
    include "juce_gui_basics/juce_gui_basics.h"
    proc isInterestedInTextDrag(text: constptr[String]): bool = discard
    proc textDropped(text: constptr[String], x: cint, y: cint) = discard

proc newCustomTextDragAndDropTarget*(): ptr CustomTextDragAndDropTarget {.importcpp: "(new june::CustomTextDragAndDropTarget)".}

proc setIsInterestedInTextDragHandler*(this: var CustomTextDragAndDropTarget, handler: proc(text: ptr String): bool {.closure.}) =
    this.onIsInterestedInTextDrag = bindClosure(handler)

proc setTextDroppedHandler*(this: var CustomTextDragAndDropTarget, handler: proc(text: ptr String, x: cint, y: cint) {.closure.}) =
    this.onTextDropped = bindClosure(handler)

defineCppClassInternal CustomTextInputTarget of TextInputTarget:
    include "juce_gui_basics/juce_gui_basics.h"
    proc isTextInputActive(): bool {.cppconst.} = discard
    proc getHighlightedRegion(): Range[cint] {.cppconst.} = discard
    proc setHighlightedRegion(newRange: constptr[Range[cint]]) = discard
    proc setTemporaryUnderlining(underlinedRegions: constptr[Array[Range[cint]]]) = discard
    proc getTextInRange(range: constptr[Range[cint]]): String {.cppconst.} = discard
    proc insertTextAtCaret(textToInsert: constptr[String]) = discard
    proc getCaretPosition(): cint {.cppconst.} = discard
    proc getCaretRectangleForCharIndex(characterIndex: cint): Rectangle[cint] {.cppconst.} = discard
    proc getTotalNumChars(): cint {.cppconst.} = discard
    proc getCharIndexForPoint(point: Point[cint]): cint {.cppconst.} = discard
    proc getTextBounds(textRange: Range[cint]): RectangleList[cint] {.cppconst.} = discard

proc newCustomTextInputTarget*(): ptr CustomTextInputTarget {.importcpp: "(new june::CustomTextInputTarget)".}

proc setIsTextInputActiveHandler*(this: var CustomTextInputTarget, handler: proc(): bool {.closure.}) =
    this.onIsTextInputActive = bindClosure(handler)

proc setGetHighlightedRegionHandler*(this: var CustomTextInputTarget, handler: proc(): Range[cint] {.closure.}) =
    this.onGetHighlightedRegion = bindClosure(handler)

proc setSetHighlightedRegionHandler*(this: var CustomTextInputTarget, handler: proc(newRange: ptr Range[cint]) {.closure.}) =
    this.onSetHighlightedRegion = bindClosure(handler)

proc setSetTemporaryUnderliningHandler*(this: var CustomTextInputTarget, handler: proc(underlinedRegions: ptr Array[Range[cint]]) {.closure.}) =
    this.onSetTemporaryUnderlining = bindClosure(handler)

proc setGetTextInRangeHandler*(this: var CustomTextInputTarget, handler: proc(range: ptr Range[cint]): String {.closure.}) =
    this.onGetTextInRange = bindClosure(handler)

proc setInsertTextAtCaretHandler*(this: var CustomTextInputTarget, handler: proc(textToInsert: ptr String) {.closure.}) =
    this.onInsertTextAtCaret = bindClosure(handler)

proc setGetCaretPositionHandler*(this: var CustomTextInputTarget, handler: proc(): cint {.closure.}) =
    this.onGetCaretPosition = bindClosure(handler)

proc setGetCaretRectangleForCharIndexHandler*(this: var CustomTextInputTarget, handler: proc(characterIndex: cint): Rectangle[cint] {.closure.}) =
    this.onGetCaretRectangleForCharIndex = bindClosure(handler)

proc setGetTotalNumCharsHandler*(this: var CustomTextInputTarget, handler: proc(): cint {.closure.}) =
    this.onGetTotalNumChars = bindClosure(handler)

proc setGetCharIndexForPointHandler*(this: var CustomTextInputTarget, handler: proc(point: Point[cint]): cint {.closure.}) =
    this.onGetCharIndexForPoint = bindClosure(handler)

proc setGetTextBoundsHandler*(this: var CustomTextInputTarget, handler: proc(textRange: Range[cint]): RectangleList[cint] {.closure.}) =
    this.onGetTextBounds = bindClosure(handler)

defineCppClassInternal CustomToolbarItemComponent of ToolbarItemComponent:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getToolbarItemSizes(toolbarThickness: cint, isToolbarVertical: bool, preferredSize: varref[cint], minSize: varref[cint], maxSize: varref[cint]): bool = discard
    proc paintButtonArea(g: varref[Graphics], width: cint, height: cint, isMouseOver: bool, isMouseDown: bool) = discard
    proc contentAreaChanged(newBounds: constptr[Rectangle[cint]]) = discard

proc newCustomToolbarItemComponent*(itemId: cint, labelText: String, isBeingUsedAsAButton: bool): ptr CustomToolbarItemComponent {.importcpp: "(new june::CustomToolbarItemComponent(@))".}

proc setGetToolbarItemSizesHandler*(this: var CustomToolbarItemComponent, handler: proc(toolbarThickness: cint, isToolbarVertical: bool, preferredSize: ptr cint, minSize: ptr cint, maxSize: ptr cint): bool {.closure.}) =
    this.onGetToolbarItemSizes = bindClosure(handler)

proc setPaintButtonAreaHandler*(this: var CustomToolbarItemComponent, handler: proc(g: ptr Graphics, width: cint, height: cint, isMouseOver: bool, isMouseDown: bool) {.closure.}) =
    this.onPaintButtonArea = bindClosure(handler)

proc setContentAreaChangedHandler*(this: var CustomToolbarItemComponent, handler: proc(newBounds: ptr Rectangle[cint]) {.closure.}) =
    this.onContentAreaChanged = bindClosure(handler)

defineCppClassInternal CustomToolbarItemFactory of ToolbarItemFactory:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getAllToolbarItemIds(ids: varref[Array[cint]]) = discard
    proc getDefaultItemSet(ids: varref[Array[cint]]) = discard
    proc createItem(itemId: cint): ptr ToolbarItemComponent = discard

proc newCustomToolbarItemFactory*(): ptr CustomToolbarItemFactory {.importcpp: "(new june::CustomToolbarItemFactory)".}

proc setGetAllToolbarItemIdsHandler*(this: var CustomToolbarItemFactory, handler: proc(ids: ptr Array[cint]) {.closure.}) =
    this.onGetAllToolbarItemIds = bindClosure(handler)

proc setGetDefaultItemSetHandler*(this: var CustomToolbarItemFactory, handler: proc(ids: ptr Array[cint]) {.closure.}) =
    this.onGetDefaultItemSet = bindClosure(handler)

proc setCreateItemHandler*(this: var CustomToolbarItemFactory, handler: proc(itemId: cint): ptr ToolbarItemComponent {.closure.}) =
    this.onCreateItem = bindClosure(handler)

defineCppClassInternal CustomTooltipClient of TooltipClient:
    include "juce_gui_basics/juce_gui_basics.h"
    proc getTooltip(): String = discard

proc newCustomTooltipClient*(): ptr CustomTooltipClient {.importcpp: "(new june::CustomTooltipClient)".}

proc setGetTooltipHandler*(this: var CustomTooltipClient, handler: proc(): String {.closure.}) =
    this.onGetTooltip = bindClosure(handler)

defineCppClassInternal CustomTreeViewItem of TreeViewItem:
    include "juce_gui_basics/juce_gui_basics.h"
    proc mightContainSubItems(): bool = discard

proc newCustomTreeViewItem*(): ptr CustomTreeViewItem {.importcpp: "(new june::CustomTreeViewItem)".}

proc setMightContainSubItemsHandler*(this: var CustomTreeViewItem, handler: proc(): bool {.closure.}) =
    this.onMightContainSubItems = bindClosure(handler)

# Withheld, with the reason:
#   AccessibilityCellInterface: const AccessibilityHandler * returned by getTableHandler has no Nim spelling
#   AccessibilityTableInterface: const AccessibilityHandler * returned by getCellHandler has no Nim spelling
#   ApplicationCommandTarget: Array<CommandID> & in getAllCommands has no Nim spelling
#   ComponentPeer: a pure virtual is private, so no subclass can implement it
#   ComponentTraverser: std::vector<Component *> returned by getAllComponents has no Nim spelling
#   DrawableShape: abstract with no overridable pure virtual
#   MultiDocumentPanel: std::function<void (bool)> in tryToCloseDocumentAsync has no Nim spelling
#   ThreadWithProgressWindow: abstract with no overridable pure virtual
