# June - Copyright (c) 2022 Lucio Asnaghi, Gavin Ray
#
# Licensed and distributed under the
#   MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#
# This file may not be copied, modified, or distributed except according to those terms.

# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomUndoableAction of UndoableAction:
    include "juce_data_structures/juce_data_structures.h"
    proc perform(): bool = discard
    proc undo(): bool = discard

proc newCustomUndoableAction*(): ptr CustomUndoableAction {.importcpp: "(new june::CustomUndoableAction)".}

proc setPerformHandler*(this: var CustomUndoableAction, handler: proc(): bool {.closure.}) =
    this.onPerform = bindClosure(handler)

proc setUndoHandler*(this: var CustomUndoableAction, handler: proc(): bool {.closure.}) =
    this.onUndo = bindClosure(handler)

defineCppClassInternal CustomValueListener of ValueListener:
    include "juce_data_structures/juce_data_structures.h"
    cppParent "juce::Value::Listener"
    proc valueChanged(value: varref[Value]) = discard

proc newCustomValueListener*(): ptr CustomValueListener {.importcpp: "(new june::CustomValueListener)".}

proc setValueChangedHandler*(this: var CustomValueListener, handler: proc(value: ptr Value) {.closure.}) =
    this.onValueChanged = bindClosure(handler)

defineCppClassInternal CustomValueTreeSynchroniser of ValueTreeSynchroniser:
    include "juce_data_structures/juce_data_structures.h"
    proc stateChanged(encodedChange: constrawptr[pointer], encodedChangeSize: csize_t) = discard

proc newCustomValueTreeSynchroniser*(tree: ValueTree): ptr CustomValueTreeSynchroniser {.importcpp: "(new june::CustomValueTreeSynchroniser(@))".}

proc setStateChangedHandler*(this: var CustomValueTreeSynchroniser, handler: proc(encodedChange: pointer, encodedChangeSize: csize_t) {.closure.}) =
    this.onStateChanged = bindClosure(handler)

# Withheld, with the reason:
#   ValueValueSource: var returned by getValue has no Nim spelling
