# Generated by tools/generate_subclasses.py. Do not edit.
#
# A JUCE class with a pure virtual cannot be constructed, so one with no
# C++ subclass is unreachable from Nim however completely its methods are
# bound. Each of these is that subclass: a std::function per override, set
# through the matching handler setter.

defineCppClassInternal CustomExpressionScopeVisitor of ExpressionScopeVisitor:
    include "juce_core/juce_core.h"
    cppTypeName ExpressionScope, "Expression::Scope"
    cppParent "juce::Expression::Scope::Visitor"
    proc visit(arg0: constptr[ExpressionScope]) = discard

proc newCustomExpressionScopeVisitor*(): ptr CustomExpressionScopeVisitor {.importcpp: "(new june::CustomExpressionScopeVisitor)".}

proc setVisitHandler*(this: var CustomExpressionScopeVisitor, handler: proc(arg0: ptr ExpressionScope) {.closure.}) =
    this.onVisit = bindClosure(handler)

defineCppClassInternal CustomFileFilter of FileFilter:
    include "juce_core/juce_core.h"
    proc isFileSuitable(file: constptr[File]): bool {.cppconst.} = discard
    proc isDirectorySuitable(file: constptr[File]): bool {.cppconst.} = discard

proc newCustomFileFilter*(filterDescription: String): ptr CustomFileFilter {.importcpp: "(new june::CustomFileFilter(@))".}

proc setIsFileSuitableHandler*(this: var CustomFileFilter, handler: proc(file: ptr File): bool {.closure.}) =
    this.onIsFileSuitable = bindClosure(handler)

proc setIsDirectorySuitableHandler*(this: var CustomFileFilter, handler: proc(file: ptr File): bool {.closure.}) =
    this.onIsDirectorySuitable = bindClosure(handler)

defineCppClassInternal CustomHighResolutionTimer of HighResolutionTimer:
    include "juce_core/juce_core.h"
    proc hiResTimerCallback() = discard

proc newCustomHighResolutionTimer*(): ptr CustomHighResolutionTimer {.importcpp: "(new june::CustomHighResolutionTimer)".}

proc setHiResTimerCallbackHandler*(this: var CustomHighResolutionTimer, handler: proc() {.closure.}) =
    this.onHiResTimerCallback = bindClosure(handler)

defineCppClassInternal CustomInputSource of InputSource:
    include "juce_core/juce_core.h"
    proc createInputStream(): ptr InputStream = discard
    proc createInputStreamFor(relatedItemPath: constptr[String]): ptr InputStream = discard
    proc hashCode(): int64 {.cppconst.} = discard

proc newCustomInputSource*(): ptr CustomInputSource {.importcpp: "(new june::CustomInputSource)".}

proc setCreateInputStreamHandler*(this: var CustomInputSource, handler: proc(): ptr InputStream {.closure.}) =
    this.onCreateInputStream = bindClosure(handler)

proc setCreateInputStreamForHandler*(this: var CustomInputSource, handler: proc(relatedItemPath: ptr String): ptr InputStream {.closure.}) =
    this.onCreateInputStreamFor = bindClosure(handler)

proc setHashCodeHandler*(this: var CustomInputSource, handler: proc(): int64 {.closure.}) =
    this.onHashCode = bindClosure(handler)

defineCppClassInternal CustomInputStream of InputStream:
    include "juce_core/juce_core.h"
    proc getTotalLength(): int64 = discard
    proc isExhausted(): bool = discard
    proc read(destBuffer: pointer, maxBytesToRead: cint): cint = discard
    proc getPosition(): int64 = discard
    proc setPosition(newPosition: int64): bool = discard

proc newCustomInputStream*(): ptr CustomInputStream {.importcpp: "(new june::CustomInputStream)".}

proc setGetTotalLengthHandler*(this: var CustomInputStream, handler: proc(): int64 {.closure.}) =
    this.onGetTotalLength = bindClosure(handler)

proc setIsExhaustedHandler*(this: var CustomInputStream, handler: proc(): bool {.closure.}) =
    this.onIsExhausted = bindClosure(handler)

proc setReadHandler*(this: var CustomInputStream, handler: proc(destBuffer: pointer, maxBytesToRead: cint): cint {.closure.}) =
    this.onRead = bindClosure(handler)

proc setGetPositionHandler*(this: var CustomInputStream, handler: proc(): int64 {.closure.}) =
    this.onGetPosition = bindClosure(handler)

proc setSetPositionHandler*(this: var CustomInputStream, handler: proc(newPosition: int64): bool {.closure.}) =
    this.onSetPosition = bindClosure(handler)

defineCppClassInternal CustomLogger of Logger:
    include "juce_core/juce_core.h"
    proc logMessage(message: constptr[String]) = discard

proc newCustomLogger*(): ptr CustomLogger {.importcpp: "(new june::CustomLogger)".}

proc setLogMessageHandler*(this: var CustomLogger, handler: proc(message: ptr String) {.closure.}) =
    this.onLogMessage = bindClosure(handler)

defineCppClassInternal CustomOutputStream of OutputStream:
    include "juce_core/juce_core.h"
    proc flush() = discard
    proc setPosition(newPosition: int64): bool = discard
    proc getPosition(): int64 = discard
    proc write(dataToWrite: constrawptr[pointer], numberOfBytes: csize_t): bool = discard

proc newCustomOutputStream*(): ptr CustomOutputStream {.importcpp: "(new june::CustomOutputStream)".}

proc setFlushHandler*(this: var CustomOutputStream, handler: proc() {.closure.}) =
    this.onFlush = bindClosure(handler)

proc setSetPositionHandler*(this: var CustomOutputStream, handler: proc(newPosition: int64): bool {.closure.}) =
    this.onSetPosition = bindClosure(handler)

proc setGetPositionHandler*(this: var CustomOutputStream, handler: proc(): int64 {.closure.}) =
    this.onGetPosition = bindClosure(handler)

proc setWriteHandler*(this: var CustomOutputStream, handler: proc(dataToWrite: pointer, numberOfBytes: csize_t): bool {.closure.}) =
    this.onWrite = bindClosure(handler)

defineCppClassInternal CustomThread of Thread:
    include "juce_core/juce_core.h"
    proc run() = discard

proc newCustomThread*(threadName: String, threadStackSize: csize_t): ptr CustomThread {.importcpp: "(new june::CustomThread(@))".}

proc setRunHandler*(this: var CustomThread, handler: proc() {.closure.}) =
    this.onRun = bindClosure(handler)

defineCppClassInternal CustomThreadListener of ThreadListener:
    include "juce_core/juce_core.h"
    cppParent "juce::Thread::Listener"
    proc exitSignalSent() = discard

proc newCustomThreadListener*(): ptr CustomThreadListener {.importcpp: "(new june::CustomThreadListener)".}

proc setExitSignalSentHandler*(this: var CustomThreadListener, handler: proc() {.closure.}) =
    this.onExitSignalSent = bindClosure(handler)

defineCppClassInternal CustomThreadPoolJob of ThreadPoolJob:
    include "juce_core/juce_core.h"
    cppTypeName ThreadPoolJobJobStatus, "ThreadPoolJob::JobStatus"
    proc runJob(): basescalar[ThreadPoolJobJobStatus] = discard

proc newCustomThreadPoolJob*(name: String): ptr CustomThreadPoolJob {.importcpp: "(new june::CustomThreadPoolJob(@))".}

proc setRunJobHandler*(this: var CustomThreadPoolJob, handler: proc(): cint {.closure.}) =
    this.onRunJob = bindClosure(handler)

defineCppClassInternal CustomThreadPoolJobSelector of ThreadPoolJobSelector:
    include "juce_core/juce_core.h"
    cppParent "juce::ThreadPool::JobSelector"
    proc isJobSuitable(job: ptr ThreadPoolJob): bool = discard

proc newCustomThreadPoolJobSelector*(): ptr CustomThreadPoolJobSelector {.importcpp: "(new june::CustomThreadPoolJobSelector)".}

proc setIsJobSuitableHandler*(this: var CustomThreadPoolJobSelector, handler: proc(job: ptr ThreadPoolJob): bool {.closure.}) =
    this.onIsJobSuitable = bindClosure(handler)

defineCppClassInternal CustomTimeSliceClient of TimeSliceClient:
    include "juce_core/juce_core.h"
    proc useTimeSlice(): cint = discard

proc newCustomTimeSliceClient*(): ptr CustomTimeSliceClient {.importcpp: "(new june::CustomTimeSliceClient)".}

proc setUseTimeSliceHandler*(this: var CustomTimeSliceClient, handler: proc(): cint {.closure.}) =
    this.onUseTimeSlice = bindClosure(handler)

defineCppClassInternal CustomURLDownloadTaskListener of URLDownloadTaskListener:
    include "juce_core/juce_core.h"
    cppTypeName URLDownloadTask, "URL::DownloadTask"
    cppParent "juce::URL::DownloadTaskListener"
    proc finished(task: ptr URLDownloadTask, success: bool) = discard

proc newCustomURLDownloadTaskListener*(): ptr CustomURLDownloadTaskListener {.importcpp: "(new june::CustomURLDownloadTaskListener)".}

proc setFinishedHandler*(this: var CustomURLDownloadTaskListener, handler: proc(task: ptr URLDownloadTask, success: bool) {.closure.}) =
    this.onFinished = bindClosure(handler)

defineCppClassInternal CustomUnitTest of UnitTest:
    include "juce_core/juce_core.h"
    proc runTest() = discard

proc newCustomUnitTest*(name: String, category: String): ptr CustomUnitTest {.importcpp: "(new june::CustomUnitTest(@))".}

proc setRunTestHandler*(this: var CustomUnitTest, handler: proc() {.closure.}) =
    this.onRunTest = bindClosure(handler)

