"""Fail if something this repository requires of itself is not true.

Each check returns a bool that feeds this script's exit status. Together
they cover what a test suite cannot state for itself: that every
hand-written binding is called, that generated subclasses, handler setters,
constructors, constants, statics, fields and inherited methods are
exercised, that a withheld begin() names an iterator that exists, that a
macOS-only method is called only under a platform guard, and that every
file carries the project's copyright notice exactly once.

The first of those is the one this file is named for.

The generated modules are checked by the generator itself: it reproduces them
byte for byte, and CI compares. The hand-written layer - june_juce_types,
june_stl, june_common, june_function_utils and the _lifting files - has no such
check, and an importcpp string only reaches the C++ compiler at the call site.
A binding nothing calls is therefore never compiled at all.

That is not hypothetical. Seven defects were found in that layer by calling
things for the first time: a BorderSize constructor JUCE does not declare, four
container types with no constructor at all, three Range setters that mutated a
let binding, and a SparseSet with no way to add to it. Every one of them
compiled cleanly for as long as nothing used it.

What is checked is a NAME, not a declaration. Six procs are called isNil and
eight iterators are called items, and one call of either satisfies all of them.

Operators are outside this check, and cannot be brought inside it as it stands.
The pattern captures a word, so a backtick-wrapped `==`, `[]` or `=destroy` never
matches - about sixty declarations. Widening the pattern would not help: an
operator is reached through SYNTAX rather than by name, so a test writes x[i]
and never the word `[]`, and a lifetime hook like `=destroy` is called by the
compiler and by nothing else. A text search cannot see either. What covers them
instead is the compile harness, which instantiates the types, and the erroring
`==` the generator emits where C++ declares none - both of which fail at
compile time rather than here.
That is the limit of a check built on a text search: it catches a binding
nothing mentions, which is the case every defect above was found in, and it
does not catch one overload of a name something else already calls.

Run from the repository root. Exits non-zero and names what is uncovered.
"""
import glob
import pathlib
import os
import subprocess
import re
import sys

# Generated by tools/generate_compile_harness.py, and matched by the test glob
# below like any other file under tests/. It casts a null pointer, calls
# through it inside a branch that is false at run time, and constructs nothing.
GENERATED_HARNESS = "tests/test_juce_compiles.nim"


def test_sources(*, count_harness):
    """The test and example sources every check below searches.

    `count_harness` has no default, so a new check has to answer the question.

    The rule: count the harness only where the harness itself calls the very
    binding the check is about. It emits a call for each importcpp proc in the
    five generated modules that takes a `this` receiver, and that call really
    is handed to the C++ compiler, so it is honest coverage for the four checks
    that ask exactly that - the constants it passes as enum arguments, the
    static variables and restated methods it calls, and the field getters it
    reads.

    Everywhere else it is not coverage but a coincidence of names, because
    those checks are about declarations the harness cannot call at all: a
    constructor, a generated subclass, a handler setter, or a hand-written proc
    in a file the harness never reads. A match there means some generated
    method happens to share the name.

    check_classes is the case that made this worth doing. It searches for the
    class NAME rather than a call, and the harness spells every receiver as
    nowhere[Class]()[], so it names every class that has one method - which
    would satisfy "a new class must not arrive with no test at all" for a class
    nothing constructs and no test drives. Exactly one class was already in
    that position, and it stayed honest only because it is listed as
    unreachable for an unrelated reason.
    """
    text = ""
    for pattern in ("tests/test_juce_*.nim", "examples/*.nim"):
        for path in sorted(glob.glob(pattern)):
            if path == GENERATED_HARNESS and not count_harness:
                continue
            text += open(path).read()
    return text


hand_written = [
    "june_juce_types.nim", "june_stl.nim", "june_common.nim",
    # june_cpp_utils exports the defineCppClass macros. It was left out, so
    # they were checked by nothing; both are called, so listing it costs
    # nothing and closes the hole by file as the keyword above closes it by
    # declaration.
    "june_cpp_utils.nim",
    "june_function_utils.nim", "juce_core_lifting.nim", "juce_events_lifting.nim",
    "juce_graphics_lifting.nim", "juce_gui_basics_lifting.nim",
    "juce_data_structures_lifting.nim",
]

# Each needs a reason, and the reason has to be why a test cannot call it
# rather than that nobody has yet.
uncallable = {}

# `macro` belongs here with the rest. A macro is only checked where it is
# expanded, exactly as an importcpp proc is only checked where it is called, so
# a macro nothing expands is unverified in the same way and for the same
# reason. Omitting the keyword left this gate reporting every hand-written
# binding covered while it could not see that kind of export at all.
#
# The backtick group matches an OPERATOR name. `\w+` cannot: it stops at the
# first punctuation, so `==`, `[]`, `$`, `=destroy` and the rest matched
# nothing at all. Fifty-two of the three hundred and eighteen exported
# declarations here were invisible, and this gate printed "all N hand-written
# binding names are called" without ever having looked at one of them.
# A receiver type nothing can name, with the reason. Empty: every type
# carrying a hand-written binding is named by a test today.
unnameable_receivers = {}

# The first parameter, whatever it is called.
#
# This required the literal name `this`, which is what the generated modules
# spell a receiver and what most of the hand-written layer copies. It is not
# what all of it spells: june_function_utils.nim names every one of its
# receivers `f`, so none of the CppFunctionObject types entered the check at
# all. The gate then printed "all 45 receiver types ... are named by a test"
# while the widened pattern finds 81 - and among the 36 it had never looked at
# were the eighteen CppFunctionObject types whose `invoke` overloads no test
# called, so seventeen importcpp strings had never been handed to a C++
# compiler. A check that cannot fail is worse than no check.
#
# The type is taken after any var/ptr/ref/sink/lent, and counts only if
# sources/june DECLARES it. That is what keeps a first parameter from being
# read as a receiver when it is not one. `varargs[untyped]` on a macro and the
# `T` of a generic are not types a test could name, and `int`, `string` and
# `cstring` are Nim's rather than this library's - a test "naming" int is a
# word search that cannot fail. Declared-in-sources is the property that
# separates those from a real receiver, and it needs no list to maintain.
receiver = re.compile(
    r'(?:proc|iterator|template|converter|macro) `?([\w=$\[\]]+)`?\*'
    r'(?:\[[^\]]*\])?\(\w+: (?:(?:var|ptr|ref|sink|lent) )*([A-Za-z_]\w*)')

# `type X* = ...` on one line, and an indented entry in a `type` block.
type_declaration = re.compile(r'^type (\w+)')
type_block_entry = re.compile(r'^\s+(\w+)\*?\s*(?:\[[^\]]*\])?\s*'
                              r'(?:\{\.[^}]*\.\})?\s*=')

export = re.compile(
    r'(?:proc|iterator|template|converter|macro) (`[^`]+`|\w+)\*')

# Every exported operator, and how it is verified.
#
# An operator is applied as SYNTAX - `a == b`, `$x`, `s[i]` - and never as
# `a.==(b)`, so the by-name search below cannot find its call sites. Widening
# the pattern alone would report all nine as uncalled; one blanket exemption
# would report all nine as covered. Both are false, so each name says how it is
# actually checked, and each way of checking is mechanical.
#
# "applied": a fragment of the tests that applies the operator, which has to
# still be there. Chosen so it can only mean this declaration - `makeString
# ("aa") < makeString("bb")` rather than a StringRef on the left, which picks
# the generated `<`(StringRef, String) instead.
#
# "no binding": every declaration of that name carries no importcpp, so there
# is no C++ string for a call site to compile and this gate's premise does not
# apply to it. Checked against the declarations rather than promised: adding
# one with an importcpp fails the gate and asks for a fragment instead.
#
# The by-name limit of the rest of this file applies here too. One fragment
# covers a NAME, so `<` is witnessed by String and the CppTypeIndex `<` beside
# it rides on that. That is the same trade the file makes everywhere else.
APPLIED, NO_BINDING = "applied", "no binding"

operator_uses = {
    "$": (APPLIED, '$greeting'),
    "()": (APPLIED, '`()`(native, noArguments.addr)'),
    "<": (APPLIED, 'makeString("aa") < makeString("bb")'),
    "<=": (APPLIED, 'makeString("aa") <= makeString("aa")'),
    "==": (APPLIED, 'makeRange(0.cint, 10.cint) == makeRange(0.cint, 10.cint)'),
    "[]": (APPLIED, 'table[0.cint].getRed()'),
    "[]=": (APPLIED, 'headers[makeString("accept")] = makeString("text/plain")'),
    # Spelled as a call rather than as `target = 13`, because the name carries
    # the type: Nim's assignment operator for juce_var is not plain `=`.
    "juce_var=": (APPLIED, '`juce_var=`(target, 13)'),
    # `=destroy` is `= discard` and `=copy` is `{.error.}`. Neither names a C++
    # expression, and `=copy` is a deletion marker whose whole purpose is that
    # reaching it is a compile error - a test that called one could not build.
    "=destroy": (NO_BINDING, None),
    "=copy": (NO_BINDING, None),
}

# The generator withholds a C++ begin()/end() pair with a reason that promises
# a Nim iterator in its place. Nothing checked that the promise held, and for
# one class it did not.
iterator_promise = re.compile(
    r'# proc (?:begin|cbegin)\*\(this: (?:var )?(\w+)\).*loop with the Nim iterator')

nim_iterator = re.compile(r'iterator \w+\*(?:\[[^\]]*\])?\(this: (?:var )?(\w+)')

# A class whose begin() is withheld and that gets no Nim iterator anyway. The
# reason has to be why a Nim iterator cannot exist.
no_iterator_possible = {
    "AndroidDocumentIterator":
        "Android only. JUCE declares it on every platform but implements it "
        "behind JUCE_ANDROID, so there is nothing for an iterator to call.",
}


implicit_default = re.compile(
    r'proc (make\w+)\*\(\): \w+ \{[^}]*\}\s*# implicit default constructor')


subclass_constructor = re.compile(r'proc (newCustom\w+)\*\(')

# A generated subclass a test cannot build. The reason has to be why a test
# cannot, not that nobody has yet.
unbuildable_subclasses = {
    "newCustomJUCEApplicationBase":
        "trips JUCE's assertion that the process has a single application "
        "instance, the same as newApplication",
    "newCustomThreadWithProgressWindow":
        "is a top-level window, and building one on a headless Linux "
        "container segfaults, the same as AlertWindow",
}


def check_subclasses():
    """Every generated subclass is built by a test.

    The C++ class lives in a header the Nim type carries, and Nim includes it
    only where the type is used - so a constructor nothing calls is never
    compiled, and neither is the class. Two real defects were sitting behind
    that: an ImagePixelData::clone override typed against the wrong class's
    Ptr, and a ComponentMovementWatcher subclass that overrode one of three
    pure virtuals and was still abstract.

    Discarding the returned pointer does not count, because the type never
    enters the translation unit. The names here are matched textually, so a
    test has to name the constructor - which it does by using what it returns.
    """
    emitted = set()
    for path in (glob.glob("sources/june/*_subclasses.nim")
                 + glob.glob("sources/june/*_lifting.nim")):
        emitted.update(subclass_constructor.findall(open(path).read()))

    used = test_sources(count_harness=False)

    uncalled = sorted(name for name in emitted
                      if name not in unbuildable_subclasses
                      and not re.search(r"\b" + name + r"\b", used))
    stale = sorted(name for name in unbuildable_subclasses
                   if name not in emitted)

    if uncalled:
        print("These generated subclasses are never built by a test, so "
              "nothing compiles the C++ class:", file=sys.stderr)
        for name in uncalled:
            print(f"  {name}", file=sys.stderr)
    if stale:
        print("These are listed as unbuildable but no longer exist:",
              file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)

    if not (uncalled or stale):
        print(f"all {len(emitted) - len(unbuildable_subclasses)} generated "
              f"subclasses are built by a test "
              f"({len(unbuildable_subclasses)} listed as unbuildable)")
    return not (uncalled or stale)


handler_setter = re.compile(r'proc (set\w+Handler)\*\(')

# A handler setter no test can call. The reason has to be why a test cannot.
uncallable_handlers = {
    name: ("is on CustomJUCEApplicationBase, and building one trips JUCE's "
           "assertion that the process has a single application instance")
    for name in (
        "setGetApplicationNameHandler", "setGetApplicationVersionHandler",
        "setMoreThanOneInstanceAllowedHandler", "setInitialiseHandler",
        "setShutdownHandler", "setAnotherInstanceStartedHandler",
        "setSystemRequestedQuitHandler", "setSuspendedHandler",
        "setResumedHandler", "setUnhandledExceptionHandler")
}


no_argument_constructor = re.compile(r'^proc (make\w+)\*\(\):', re.M)

# A constructor for a class that exists on one platform only. The committed
# generated files are the macOS output, so these are declared everywhere and
# defined only there, and a test that called one would not build on Linux.
platform_specific_constructors = {
    "makeScopedAutoReleasePool":
        "juce::ScopedAutoReleasePool is an Objective-C autorelease pool and "
        "exists on macOS only",
}


def check_no_argument_constructors():
    """Every generated constructor that takes no arguments is called.

    Only constructors, and only the no-argument ones. Sweeping the const
    getters on every default-constructible class was tried too and abandoned
    for the same reason: makeThreadPool starts threads, makeStreamingSocket
    and makeChildProcess do real work, and the process was killed rather than
    finishing. It did find one thing before it was dropped - AndroidDocument
    ::getNativeInfo returns a type JUCE only forward declares - and that is
    named in the generator now.

    A sweep that invents arguments was tried and abandoned: a JUCE constructor does real work, and the invented values sent
    it doing it - a directory handed to ZipFile, an empty name to
    InterProcessLock - until the process was killed. Compiling the importcpp is
    not worth running JUCE against nonsense, so the 191 constructors that take
    arguments stay uncovered unless a test has a real reason to build one.

    Sweeping the no-argument ones is what found five constructors emitted for a
    deleted C++ one - JSONUtils,
    OrderedContainerHelpers, WindowUtils, ContentSharer and String(bool),
    which JUCE deletes so that a bool does not silently become a String.
    """
    emitted = set()
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        emitted.update(no_argument_constructor.findall(
            open(f"sources/june/{module}.nim").read()))

    used = test_sources(count_harness=False)

    uncalled = sorted(name for name in emitted
                      if name not in platform_specific_constructors
                      and not re.search(r"\b" + name + r"\b", used))

    # An exemption naming a constructor the generator no longer emits excuses
    # nothing, and its reason stops being checked against anything. Every other
    # exemption list in this file is held to that; this one was not.
    stale = sorted(name for name in platform_specific_constructors
                   if name not in emitted)

    if uncalled:
        print("These no-argument constructors are never called, so nothing "
              "compiles them:", file=sys.stderr)
        for name in uncalled:
            print(f"  {name}", file=sys.stderr)
    if stale:
        print("These are listed as platform specific but are no longer "
              "emitted:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
    if uncalled or stale:
        return False

    print(f"all {len(emitted) - len(platform_specific_constructors)} "
          f"no-argument constructors are called "
          f"({len(platform_specific_constructors)} is platform specific)")
    return True


bound_constant = re.compile(r'^let (\w+)\* \{[^}]*importcpp:', re.M)


constructible_class = re.compile(r'^proc make(\w+)\*\(', re.M)

# A class a test cannot reach. The reason has to be why, not that nobody has.
unreachable_classes = {
    "NetworkServiceDiscoveryAvailableServiceList":
        "opens a UDP socket to listen for service announcements",
    "NetworkServiceDiscoveryAdvertiser":
        "opens a UDP socket to broadcast announcements",
    "AndroidDocumentInputSource": "exists on Android only",
    "ScopedAutoReleasePool":
        "is an Objective-C autorelease pool and exists on macOS only, while "
        "the committed generated files are the macOS output",
}


def check_classes():
    """Every class with a constructor is named by a test.

    Weaker than the other checks here - a name in a test file is not proof the
    class was driven - but it is what stops a new class from arriving with no
    test at all, which is how every defect this branch fixed stayed hidden.
    """
    emitted = set()
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        emitted.update(constructible_class.findall(
            open(f"sources/june/{module}.nim").read()))

    used = test_sources(count_harness=False)

    # Substring, not a word boundary: a class is often reached through
    # make<Name>, and <Name> has no boundary before it there.
    untested = sorted(name for name in emitted
                      if name not in unreachable_classes and name not in used)
    stale = sorted(name for name in unreachable_classes if name not in emitted)

    if untested:
        print("These classes have a constructor and are named by no test:",
              file=sys.stderr)
        for name in untested:
            print(f"  {name}", file=sys.stderr)
    if stale:
        print("These are listed as unreachable but have no constructor:",
              file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)

    if not (untested or stale):
        print(f"all {len(emitted) - len(unreachable_classes)} constructible "
              f"classes are named by a test "
              f"({len(unreachable_classes)} listed as unreachable)")
    return not (untested or stale)


inherited_method = re.compile(
    r'^proc (\w+)\*\(this: (?:var )?(?:typedesc\[)?(\w+)[,)\]][^\n]*'
    r'# inherited from a secondary base$', re.M)


# Restated methods a test cannot call, with the reason it cannot. Same shape as
# the exclusion tables the other checks carry: the entry has to say what stops
# a test, not that writing one is inconvenient.
uncallable_inherited = {
    "setCurrentDragImage":
        "JUCE writes through dragImageComponents[0] without checking it exists "
        "(juce_DragAndDropContainer.cpp:570), so it segfaults unless a drag is "
        "already running, and starting a real one needs a dragging mouse",
    "startDragging":
        "needs a MouseInputSource that is actually dragging; with none it "
        "trips two jasserts and starts nothing",
    "performExternalDragDropOfFiles":
        "hands the payload to the operating system's drag service, so calling "
        "it would start a real drag on the machine running the tests",
    "performExternalDragDropOfText":
        "hands the payload to the operating system's drag service, so calling "
        "it would start a real drag on the machine running the tests",
    "findFirstTargetParentComponent":
        "reached only through a JUCEApplication, whose constructor asserts "
        "unless it is the process's one application instance",
    "getTargetForCommand":
        "reached only through a JUCEApplication, whose constructor asserts "
        "unless it is the process's one application instance",
    "invoke":
        "reached only through a JUCEApplication, whose constructor asserts "
        "unless it is the process's one application instance",
    "isCommandActive":
        "reached only through a JUCEApplication, whose constructor asserts "
        "unless it is the process's one application instance",
}


# Nim integer types an integer literal converts to at equal cost, which is what
# makes an overload set of them ambiguous for a plain literal.
nim_integer_types = {
    "cint", "int8", "int16", "int32", "int64",
    "uint8", "uint16", "uint32", "uint64", "csize_t",
    "cshort", "cushort", "clong", "culong", "clonglong", "culonglong",
}

# Overload sets where an int-taking forwarder would have no lossless target,
# with the reason. A caller passes the width for these.
no_lossless_int_target = {
    "swap": "each overload returns its own width, so an int form would have to "
            "pick one return type and no choice is the obvious one",
    "countNumberOfBits": "takes only uint32 and uint64, and a Nim int is signed",
    "makeGridPx": "takes only cint and uint64, so neither is lossless for a Nim int",
    "makeGridFr": "takes only cint and uint64, so neither is lossless for a Nim int",
    "read": "takes only cint and uint64, and the two overloads return different types",
}


# A field accessor a test cannot reach, with the reason it cannot. The reason
# has to be why a test cannot, not that nobody has written one.
unreachable_fields = {
    "clip":
        "belongs to ColourLayer, which holds an EdgeTable and so has no "
        "default constructor, and JUCE hands one out from nothing that is "
        "bound",
    "directoryContentsList":
        "belongs to DirectoryContentsDisplayComponent, which is a secondary "
        "base of FileListComponent and FileTreeComponent; Nim carries one "
        "parent and both take the other, so no bound class reaches the field",
}

field_getter = re.compile(
    r'^proc (\w+)\*\(this: (?:var )?(\w+)\)[^{]*\{[^}]*importcpp: "#\.\1"', re.M)
field_setter = re.compile(
    r'^proc `(\w+)=`\*\(this: var (\w+)[^{]*\{[^}]*importcpp: "#\.\1 = ', re.M)


def check_field_accessors():
    """Every public field is written and read by a test.

    A field getter and setter are importcpp procs like any other: they reach
    the C++ compiler only where something calls them, so a setter nothing
    assigns is never compiled. Nine of them assigned a move-only wrapper by
    copy and were rejected at every call site, and two more named a type with
    no copy constructor at all - each found by writing the assignment.

    Identified by the shape of the importcpp rather than the signature: a
    getter is a bare member read and a setter a member assignment, which is
    what tells them apart from an ordinary method.

    Keyed on the field's NAME, because the receiver's type is not written at
    the call site and this reads the test source rather than compiling it. Two
    classes with a field of the same name therefore cover each other:
    FlexBox.alignContent and Grid.alignContent are one entry here, and only one
    of them has to be assigned. Verified against a name that belongs to a
    single class - removing the assignment to
    ComponentPaintDiagnostics.wroteToCache makes this fail and name it.
    """
    getters, setters = set(), set()
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        text = open(f"sources/june/{module}.nim").read()
        getters.update(name for name, _ in field_getter.findall(text))
        setters.update(name for name, _ in field_setter.findall(text))

    used = test_sources(count_harness=True)

    unread = sorted(name for name in getters
                    if name not in unreachable_fields
                    and not re.search(r"\." + name + r"\b", used))
    unwritten = sorted(name for name in setters
                       if name not in unreachable_fields
                       and not re.search(r"\." + name + r"\s*=[^=]", used))

    stale = sorted(name for name in unreachable_fields
                   if name not in getters and name not in setters)
    if stale:
        print("These entries in unreachable_fields name no field accessor:",
              file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        return False

    if unread or unwritten:
        if unread:
            print("These field getters are never read, so nothing compiles "
                  "them:", file=sys.stderr)
            for name in unread[:20]:
                print(f"  {name}", file=sys.stderr)
            if len(unread) > 20:
                print(f"  ... and {len(unread) - 20} more", file=sys.stderr)
        if unwritten:
            print("These field setters are never assigned, so nothing "
                  "compiles them:", file=sys.stderr)
            for name in unwritten[:20]:
                print(f"  {name}", file=sys.stderr)
            if len(unwritten) > 20:
                print(f"  ... and {len(unwritten) - 20} more", file=sys.stderr)
        return False

    print(f"all {len(getters)} field getters are read and all {len(setters)} "
          f"field setters are assigned by a test "
          f"({len(unreachable_fields)} listed as unreachable)")
    return True


def check_integer_literal_overloads():
    """Every overload set that can take a Nim int has a proc that does.

    JUCE gives String six integer constructors, and a plain Nim integer literal
    converts to all of them at equal cost, so `makeString(5)` is ambiguous. A
    proc taking Nim's own `int` is an exact match and wins outright.

    One is written by hand for each set that has an int64 overload and one
    return type across its integer overloads, since a Nim int IS an int64 here
    and the conversion is lossless. This recomputes the set from the generated
    files, so a JUCE upgrade that adds or removes an overload fails here rather
    than silently leaving a call ambiguous.
    """
    groups = {}
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        for line in open(f"sources/june/{module}.nim"):
            if not line.startswith("proc "):
                continue
            match = re.match(r'^proc (`?[\w=]+`?)\*\((.*?)\)(: [^{]+)? \{', line)
            if not match:
                continue
            name, body, returns = (match.group(1), match.group(2),
                                   (match.group(3) or "").strip(": ").strip())
            parts = [p for p in body.split(", ") if ":" in p]
            types = tuple(p.split(":", 1)[1].strip().split(" =")[0].strip()
                          for p in parts)
            names = tuple(p.split(":", 1)[0].strip() for p in parts)
            if not types:
                continue
            receiver = types[0] if names and names[0] == "this" else ""
            groups.setdefault((name, receiver, len(types)), []).append(
                (types, returns))

    wanted, unavailable = set(), set()
    for (name, receiver, arity), rows in groups.items():
        signatures = {row[0] for row in rows}
        if len(signatures) < 2:
            continue
        for position in range(arity):
            column = {s[position] for s in signatures}
            others_fixed = all(len({s[other] for s in signatures}) == 1
                               for other in range(arity) if other != position)
            if len(column & nim_integer_types) < 2 or not others_fixed:
                continue
            returns = {row[1] for row in rows
                       if row[0][position] in nim_integer_types}
            if "int64" in column and len(returns) == 1:
                wanted.add((name, position))
            else:
                unavailable.add(name)
            break

    written = ""
    for path in glob.glob("sources/june/*_lifting.nim"):
        written += open(path).read()

    missing = sorted(name for name, _ in wanted
                     if not re.search(r"^proc " + re.escape(name) +
                                      r"\*\([^)]*: int[,)]", written, re.M))
    if missing:
        print("These overload sets have an int64 form and one return type, so "
              "a proc taking Nim's int would resolve a literal, and none is "
              "written:", file=sys.stderr)
        for name in missing:
            print(f"  {name}", file=sys.stderr)
        return False

    stale = sorted(name for name in no_lossless_int_target
                   if name not in unavailable)
    if stale:
        print("These entries in no_lossless_int_target name a set that now has "
              "a lossless target, or no longer exists:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        return False

    print(f"all {len(wanted)} overload sets that can take a Nim int have a proc "
          f"that does ({len(unavailable)} have no lossless target)")
    return True


def check_one_declaration_per_signature():
    """No method is declared on both a class and a Nim ancestor.

    An override has the same parameter types as the virtual it overrides, so
    emitting both leaves Nim two procs differing only in the receiver. On the
    derived class itself the nearer one wins; on anything below it neither is
    nearer, and Nim 2.2.2 refuses the call as ambiguous. `paint` on a
    TableListBox was in that state, along with 50 others.

    Nothing catches this at generation time, and nothing catches it at compile
    time either unless a test happens to make the call on a deep enough
    receiver. It is a property of the emitted text, so it is checked here.

    The scan below matches a `this` receiver only, and that is deliberate rather
    than the narrowing that bit two other patterns in this file. The generated
    modules do spell some first parameters otherwise - 167 procs take `a` - but
    every one of those is a borrowed `==` over a distinct enum, a free function
    with no receiver to inherit through. The ambiguity being checked is between a
    method and the same method on a Nim ancestor, which only a receiver-taking
    proc can be in. Widening this to any first parameter would add enum
    operators, not coverage.
    """
    parents, procedures = {}, {}
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        text = open(f"sources/june/{module}.nim").read()
        parents.update(re.findall(r'^  (\w+)\*[^=\n]*= object of (\w+)', text, re.M))
        for line in text.splitlines():
            match = re.match(r'^proc (`?[\w=]+`?)\*\(this: (?:var )?(\w+)([,)])(.*)', line)
            if not match:
                continue
            name, receiver, separator, rest = match.groups()
            if separator == ")":
                arguments = ()
            else:
                body = rest.rsplit("):", 1)[0] if "):" in rest else rest.rsplit(")", 1)[0]
                arguments = tuple(part.split(":", 1)[1].strip().split(" =")[0].strip()
                                  for part in body.split(", ") if ":" in part)
            procedures.setdefault((name, receiver), set()).add(arguments)

    def ancestors(name):
        found, seen = [], set()
        while name in parents and name not in seen:
            seen.add(name)
            name = parents[name]
            found.append(name)
        return found

    children = {}
    for child, parent in parents.items():
        children.setdefault(parent, []).append(child)

    def has_descendant(name):
        return bool(children.get(name))

    # Only where a class below the derived one exists. On the derived class
    # itself Nim prefers the nearer proc, so two declarations there are
    # harmless; the ambiguity needs a receiver for which neither is nearer.
    # That distinction is what lets a covariant override stay: TableListBox
    # declares its own getModel because it returns a TableListBoxModel rather
    # than a ListBoxModel, and nothing inherits from TableListBox. A covariant
    # override on a class that DOES have descendants would land here, and it
    # would be a real conflict rather than a false alarm - the type and the
    # callability cannot both be had.
    clashes = []
    for (name, receiver), signatures in sorted(procedures.items()):
        if not has_descendant(receiver):
            continue
        for ancestor in ancestors(receiver):
            shared = signatures & procedures.get((name, ancestor), set())
            if shared:
                clashes.append(f"{name} on {receiver} and on {ancestor}")
                break

    if clashes:
        print("These are declared with the same argument types on a class and "
              "on one of its Nim ancestors, so a call on anything below the "
              "class is ambiguous:", file=sys.stderr)
        for clash in clashes[:20]:
            print(f"  {clash}", file=sys.stderr)
        if len(clashes) > 20:
            print(f"  ... and {len(clashes) - 20} more", file=sys.stderr)
        return False

    print(f"no method is declared on both a class with descendants and a Nim "
          f"ancestor ({len(procedures)} class-and-name pairs checked)")
    return True


def check_inherited_methods():
    """Every method restated from a secondary base is called by a test.

    Nim carries one parent, so a method reaching a class through any other
    public base is not inherited - it exists only because the generator
    restates it on the class. A restatement nobody calls is never handed to the
    C++ compiler, which is how the whole class of defect on this branch stayed
    invisible. Each of these is a fresh binding and gets the same treatment as
    a hand-written one.
    """
    emitted = set()
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        for method, owner in inherited_method.findall(
                open(f"sources/june/{module}.nim").read()):
            emitted.add((owner, method))

    used = test_sources(count_harness=True)

    # The receiver's type is not written at the call site, so this asks only
    # that the method name appears. Two classes inheriting the same method from
    # the same base therefore cover each other, which is why the tests below
    # name the class in the assertion message instead.
    uncalled = sorted({method for _, method in emitted
                       if method not in uncallable_inherited
                       and not re.search(r"\." + method + r"\b", used)})

    # An entry that no longer names an emitted method is stale, and a stale
    # excuse reads exactly like a live one.
    stale = sorted(name for name in uncallable_inherited
                   if name not in {method for _, method in emitted})
    if stale:
        print("These entries in uncallable_inherited name no restated method:",
              file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        return False

    if uncalled:
        print("These methods are restated from a secondary base and never "
              "called, so the C++ compiler never sees them:", file=sys.stderr)
        for name in uncalled[:25]:
            owners = sorted(o for o, m in emitted if m == name)
            print(f"  {name} on {', '.join(owners)}", file=sys.stderr)
        if len(uncalled) > 25:
            print(f"  ... and {len(uncalled) - 25} more", file=sys.stderr)
        return False

    print(f"all {len(emitted)} methods restated from a secondary base "
          f"are called by a test "
          f"({len(uncallable_inherited)} listed as uncallable)")
    return True


def without_comment(line):
    """`line` up to its comment, if it has one.

    A `#` counts as the start of a comment when an even number of double quotes
    precede it, so a `#` inside a string literal stays, and `\'#\'` is skipped
    because a character literal is not a comment either.

    Single quotes are deliberately NOT tracked as literal delimiters. Nim spells
    a numeric suffix with one - `0\'f32`, `5\'u8` - and this suite is full of
    them, so a scanner that opened a character literal on every `\'` would think
    most of the file was inside one and stop finding comments at all. That is a
    worse failure than the case it would fix, and the two-character form above
    covers the case that actually arises.
    """
    index = 0
    while index < len(line):
        if (line[index] == "#"
                and line[:index].count('"') % 2 == 0
                and not (index and line[index - 1] == "'"
                         and line[index + 1:index + 2] == "'")):
            return line[:index]
        index += 1
    return line


def check_macos_only_calls():
    """A behavioural test calling a macOS-only method does so under a guard.

    The bindings are generated ON macOS, so a method JUCE declares nowhere
    else still gets a proc here. Nim compiles the call; g++ on Linux does not,
    and the failure arrives a full CI cycle later. The compile harness already
    knows which methods these are - MACOS_ONLY_METHODS in its generator - and
    puts its own calls behind `when defined(macosx)`. This is the same rule
    for the behavioural tests, which had no check at all: File.isBundle was
    called unguarded and only Linux CI said so.

    A call counts as guarded when some enclosing line, at a smaller
    indentation, is `when defined(macosx)`. That is what the suite's own
    guards look like, and a false ALARM here is cheap to fix while a false
    all-clear is what this exists to prevent.

    The corpus is the tests AND the examples, which is what test_sources
    covers and what CI builds on ubuntu. This cannot call test_sources itself,
    because the guard is found by walking BACK through a file's lines and
    test_sources returns the files concatenated; it uses the same two patterns
    instead. Leaving examples out was not a smaller corpus but a hole in this
    exact shape: an unguarded macOS-only call in an example breaks the ubuntu
    build, which is the failure this check exists to move earlier.

    The generated harness is the one file left out. Its calls are placed under
    a guard by the generator, from the same list read here, so it would only
    ever confirm the generator against itself.

    A call is matched by the dot and the name, with no parenthesis required.
    Nim calls a no-argument method as `file.isBundle`, and requiring `(` meant
    that spelling was not seen - for File.isBundle among others, which is the
    very call that put this list in the harness.

    Dropping the parenthesis made comments matter. The required `(` had been
    excluding them by accident, and a comment in test_juce_core.nim explains
    why String.convertToPrecomposedUnicode is left out of a sweep - prose that
    named the method and then read as an unguarded call to it. So the comment
    is cut off each line first, at the first `#` with an even number of quotes
    before it, which is a comment rather than a `#` inside a string.

    What this does NOT catch: a macOS-only method that is not on that list.
    The list was built by compiling the harness on Linux, one round per error
    the compiler reported, so it holds the methods the harness had to call.
    A method covered behaviourally from the start never entered the harness
    and so never entered the list. Linux CI is still the backstop for those -
    it is what found isBundle - and a name added to MACOS_ONLY_METHODS when
    that happens brings the method under this check too.
    """
    harness = open("tools/generate_compile_harness.py").read()
    block = re.search(r"MACOS_ONLY_METHODS = \{(.*?)\n\}", harness, re.S)
    if block is None:
        print("MACOS_ONLY_METHODS is not where this expected it",
              file=sys.stderr)
        return False
    methods = set(re.findall(r'\(\s*"[A-Za-z_]\w*"\s*,\s*"([A-Za-z_]\w*)"\s*\)',
                             block.group(1)))

    # Every tuple in the block has to yield a name. Reading a list out of
    # another file with a regex is fragile in one direction only: a pattern
    # that stops matching an entry does not fail, it silently drops that
    # method from the check, and the gate then reports every call guarded
    # while no longer looking at one of them.
    # Counted by a DIFFERENT shape on purpose. An "independent" count written
    # with the same pattern as the extraction is not independent: a change that
    # stops one matching stops the other too, both fall by one, and the
    # comparison still passes. Non-comment lines holding a comma is a property
    # of the block's layout rather than of the pattern above.
    entries = [line for line in block.group(1).split("\n")
               if line.strip() and not line.strip().startswith("#")
               and "," in line]
    if len(entries) != len(methods):
        print(f"MACOS_ONLY_METHODS holds {len(entries)} entries but this "
              f"extracted {len(methods)} names, so the ones it missed are "
              f"exempt from this check without saying so", file=sys.stderr)
        return False

    unguarded = []
    paths = []
    for pattern in ("tests/test_juce_*.nim", "examples/*.nim"):
        paths += sorted(glob.glob(pattern))
    call_pattern = re.compile(
        r"\.(" + "|".join(sorted(methods)) + r")(?![A-Za-z0-9_])")
    for path in paths:
        if path == GENERATED_HARNESS:
            continue
        lines = open(path).read().splitlines()
        for number, line in enumerate(lines):
            call = call_pattern.search(without_comment(line))
            if not call:
                continue
            indent = len(line) - len(line.lstrip())
            guarded = False
            for earlier in reversed(lines[:number]):
                if not earlier.strip():
                    continue
                earlier_indent = len(earlier) - len(earlier.lstrip())
                if earlier_indent < indent:
                    if re.match(r"when defined\(macosx\):", earlier.strip()):
                        guarded = True
                        break
                    indent = earlier_indent
            if not guarded:
                unguarded.append(f"{path}:{number + 1}  {call.group(1)}")

    if unguarded:
        print("These behavioural tests call a macOS-only method without a "
              "`when defined(macosx)` guard, so they will not compile on "
              "Linux:", file=sys.stderr)
        for entry in unguarded:
            print(f"  {entry}", file=sys.stderr)
        return False

    print(f"every behavioural call to one of the {len(methods)} macOS-only "
          f"methods is guarded")
    return True


def check_constants():
    """Every bound constant is read by a test.

    A `let` with an importcpp is not checked against C++ unless something
    reads it. A constant naming juce::NoSuchClass::nope compiles clean while
    nothing touches it, which was measured rather than assumed: when this was
    first checked, most of the bound constants had never had their spelling
    put to the compiler. The count this prints is the live one.
    """
    emitted = set()
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        emitted.update(bound_constant.findall(
            open(f"sources/june/{module}.nim").read()))

    used = test_sources(count_harness=True)

    unread = sorted(name for name in emitted
                    if not re.search(r"\b" + name + r"\b", used))
    if unread:
        print("These constants are never read, so their C++ spelling is not "
              "checked:", file=sys.stderr)
        for name in unread[:20]:
            print(f"  {name}", file=sys.stderr)
        if len(unread) > 20:
            print(f"  ... and {len(unread) - 20} more", file=sys.stderr)
        return False

    print(f"all {len(emitted)} bound constants are read by a test")
    return True


static_variable = re.compile(
    r'^proc (\w+)\*\(this: typedesc\[\w+\]\): [^{]+\{[^}]*importcpp: "\(', re.M)


def check_static_variables():
    """Every bound static variable is read by a test.

    Bound as a proc over the typedesc, so it is compiled only where it is
    called - exactly like the constants, and 99 of the 111 had never had their
    C++ spelling checked.
    """
    emitted = set()
    for module in ("juce_core", "juce_events", "juce_data_structures",
                   "juce_graphics", "juce_gui_basics"):
        emitted.update(static_variable.findall(
            open(f"sources/june/{module}.nim").read()))

    used = test_sources(count_harness=True)

    unread = sorted(name for name in emitted
                    if not re.search(r"\b" + name + r"\b", used))
    if unread:
        print("These static variables are never read, so their C++ spelling "
              "is not checked:", file=sys.stderr)
        for name in unread[:20]:
            print(f"  {name}", file=sys.stderr)
        if len(unread) > 20:
            print(f"  ... and {len(unread) - 20} more", file=sys.stderr)
        return False

    print(f"all {len(emitted)} static variables are read by a test")
    return True


def check_handlers():
    """Every generated handler setter is called by a test.

    A setter nothing calls is neither type-checked in its body nor generated,
    and the C++ field it assigns to is never written. Calling them is what
    caught CustomImagePixelData::clone being typed against the wrong class's
    Ptr, and what showed that UniquePtr, ReferenceCountedObjectPtr, CppVector
    and CppString had no constructor, so no override returning one could be
    written at all.
    """
    emitted = set()
    for path in (glob.glob("sources/june/*_subclasses.nim")
                 + glob.glob("sources/june/*_lifting.nim")):
        emitted.update(handler_setter.findall(open(path).read()))

    used = test_sources(count_harness=False)

    uncalled = sorted(name for name in emitted
                      if name not in uncallable_handlers
                      and not re.search(r"\b" + name + r"\b", used))
    stale = sorted(name for name in uncallable_handlers if name not in emitted)

    if uncalled:
        print("These handler setters are never called, so nothing type-checks "
              "or generates them:", file=sys.stderr)
        for name in uncalled:
            print(f"  {name}", file=sys.stderr)
    if stale:
        print("These are listed as uncallable handlers but no longer exist:",
              file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)

    if not (uncalled or stale):
        print(f"all {len(emitted) - len(uncallable_handlers)} handler setters "
              f"are called ({len(uncallable_handlers)} listed as uncallable)")
    return not (uncalled or stale)


def check_implicit_defaults():
    """Every aggregate given an implicit default constructor is built by a test.

    libclang reports no constructor for a struct that declares none, and it
    does not report that C++ deleted the implicit one because a member has no
    default either. ColourLayer and GlyphLayer are both that case. Only a call
    tells them apart, so each of these has to be called.
    """
    emitted = set()
    for path in glob.glob("sources/june/juce_*.nim"):
        emitted.update(implicit_default.findall(open(path).read()))

    used = test_sources(count_harness=False)

    uncalled = sorted(name for name in emitted
                      if not re.search(r"\b" + name + r"\b", used))
    if uncalled:
        print("These aggregates get an implicit default constructor that no "
              "test builds, so nothing compiles it:", file=sys.stderr)
        for name in uncalled:
            print(f"  {name}", file=sys.stderr)
        return False

    print(f"all {len(emitted)} implicit default constructors are built by a test")
    return True


def check_iterator_promises():
    """Every class whose begin() was withheld naming a Nim iterator has one."""
    promised = set()
    for path in glob.glob("sources/june/juce_*.nim"):
        promised.update(iterator_promise.findall(open(path).read()))

    provided = set()
    for path in glob.glob("sources/june/*.nim"):
        provided.update(nim_iterator.findall(open(path).read()))

    broken = sorted(promised - provided - set(no_iterator_possible))
    stale = sorted(name for name in no_iterator_possible if name not in promised)

    if broken:
        print("These classes have begin() withheld with a reason that names a "
              "Nim iterator, and no such iterator exists:", file=sys.stderr)
        for name in broken:
            print(f"  {name}", file=sys.stderr)
    if stale:
        print("These are listed as having no possible iterator but no longer "
              "have a withheld begin():", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)

    if not (broken or stale):
        print(f"all {len(promised - set(no_iterator_possible))} withheld "
              f"begin() reasons name an iterator that exists "
              f"({len(no_iterator_possible)} cannot have one)")
    return not (broken or stale)


def check_gitignore_order():
    """Build output stays ignored under tests/ and examples/.

    .gitignore puts directories back under those two, so a subdirectory of test
    data is not dropped silently - git says nothing when an add matches an
    ignored path. That negation is indiscriminate: it re-admits every directory
    the general rules exclude, and .app, .dSYM, nimcache and the rest are all
    directories. What keeps them out is ORDER - the general rules come after,
    and a later rule wins.

    Order is not something a reader can see is load-bearing, and a rule that
    looks fine can still let a build artifact through - which is how a compiled
    binary reached a commit here once. So it is checked rather than described:
    each case below is asked of git itself, which is the only authority on what
    it would ignore.
    """
    must_ignore = ["tests/x.app/f", "tests/x.dSYM/f", "tests/nimcache/f",
                   "tests/build/f", "tests/__pycache__/f", "tests/somebinary",
                   "examples/x.app/f", "examples/nimcache/f"]
    must_track = ["tests/fixtures/sample", "examples/fixtures/sample",
                  "tests/test_juce_core.nim"]

    def ignored(path):
        return subprocess.run(["git", "check-ignore", "-q", path]).returncode == 0

    wrong = [p for p in must_ignore if not ignored(p)]
    wrong += [p for p in must_track if ignored(p)]
    if wrong:
        print("These paths are on the wrong side of .gitignore, which usually "
              "means the general rules no longer come after the tests/ and "
              "examples/ negations:", file=sys.stderr)
        for path in wrong:
            print(f"  {path}", file=sys.stderr)
        return False
    return True


def declared_types():
    """Every type name declared under sources/june.

    This is what tells a receiver from a first parameter that is not one. It
    reads the generated modules as well as the hand-written layer, because a
    lifting file declares bindings on JUCE classes the generator declares.
    """
    names = set()
    for path in sorted(glob.glob("sources/june/*.nim")):
        in_block = False
        with open(path) as handle:
            for line in handle:
                match = type_declaration.match(line)
                if match:
                    names.add(match.group(1))
                    in_block = True
                    continue
                if line.strip() and not line[0].isspace():
                    in_block = line.rstrip() == "type"
                    continue
                if in_block:
                    entry = type_block_entry.match(line)
                    if entry:
                        names.add(entry.group(1))
    return names


# A hand-written binding whose name the corpus contains only as prose. The
# reason has to be why a call cannot appear in a test or an example.
mentioned_not_called = {
    "defineCppClassInternal":
        "the library-side variant, invoked by the generated *_subclasses "
        "modules rather than by a test. The suite compiles those, so the macro "
        "is expanded - just not from this corpus.",
}


def check_names_are_called_not_mentioned(declared_names):
    """A hand-written binding name appears in a call, not only in prose.

    The check above asks whether the NAME occurs in the tests, and a name is an
    ordinary word. `what` on CppException was reported covered by the English
    "what" in this suite's comments, `between` on Range by "the difference
    between them", and `release` on UniquePtr by "after one release the count
    is". None of the three had ever reached a C++ compiler, which is the one
    thing this file exists to prevent.

    So the occurrence has to look like a call. Three shapes count, because Nim
    spells a call three ways: with parentheses or brackets whatever precedes it
    (`$makeStringFromUTF8(...)` counts, and the `$` is not a word boundary), by
    UFCS without them (`obj.reset`), and command-style for a macro or template
    (`defineCppClass Foo of Bar:`). Comments and string literals are removed
    first - that is the whole point.

    This is narrower than the name search and does not replace it: a name that
    is called is also mentioned, so anything this catches the other lets pass.
    """
    names = {name for name in declared_names if name.isidentifier()}

    prose = test_sources(count_harness=False)
    code = re.sub(r"#.*", "", prose)
    code = re.sub(r'"[^"\n]*"', '""', code)

    def called(name):
        spelled = re.escape(name)
        return (re.search(r"(?<![A-Za-z0-9_])" + spelled + r"\s*[(\[]", code)
                or re.search(r"\." + spelled + r"(?![A-Za-z0-9_])", code)
                or re.search(r"(?m)^\s*" + spelled + r"\s+[A-Za-z_]", code))

    mentioned = sorted(name for name in names
                       if name not in mentioned_not_called
                       and re.search(r"\b" + re.escape(name) + r"\b", prose)
                       and not called(name))
    stale = sorted(name for name in mentioned_not_called if name not in names)

    if mentioned:
        print("These names occur in the tests only as prose, so the name check "
              "above passes while nothing calls them:", file=sys.stderr)
        for name in mentioned:
            print(f"  {name}", file=sys.stderr)
    if stale:
        print("These are listed as mentioned-not-called but are no longer "
              "declared:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
    if mentioned or stale:
        return False

    print(f"all {len(names) - len(mentioned_not_called)} hand-written names "
          f"that a test mentions are spelled as a call "
          f"({len(mentioned_not_called)} is invoked outside this corpus)")
    return True


def check_receiver_types_named():
    """Every hand-written binding has a receiver some test names.

    The coverage check above matches a NAME, and a name is shared: `size`,
    `isEmpty`, `contains`, `items`, `len`, `clear` and `reset` are each declared
    on several types here and on generated JUCE classes besides. A call to any
    one of them reported all of them covered, so a binding could be reported
    exercised while its importcpp string had never reached a C++ compiler.

    That is not hypothetical. It hid std::vector::clear behind six other
    `clear`s, two iterators behind eighteen other `items`, OptionalScopedPointer
    behind unique_ptr's `release`, and eight methods on CppMap,
    CppUnorderedMap, CppArray and Optional - none of which the compile harness
    reaches either, because it skips a generic receiver.

    Checking the RECEIVER closes what the name cannot: a test that never
    mentions the type cannot have called anything on it. Matching is textual,
    so naming the type or its constructor both count.

    This is a per-TYPE check, and that is one of its two limits. It catches a
    type no test names - CppArray and Optional were both invisible that way. It
    cannot catch a method never called on a type some test DOES name:
    CppMap.isEmpty and CppUnorderedMap.`[]` were two of the eight above, and
    testStlContainers constructs both types, so nothing here would have flagged
    them. Six of the eight, not all eight.

    The other limit is what a receiver is TAKEN TO BE, and it used to be a
    first parameter literally named `this`. That is what the generated modules
    spell and what most of the hand-written layer copies, and it silently
    excluded the file that does not: june_function_utils.nim names every
    receiver `f`. Thirty-six types were outside the check, eighteen of them
    CppFunctionObject types, and seventeen `invoke` overloads had consequently
    never been handed to a C++ compiler while this printed "all 45 receiver
    types ... are named by a test" - a gate satisfied by having looked at
    nothing. The receiver is now the first parameter under any name.

    Taking any first parameter needs a rule for the ones that are not
    receivers, and the rule is that sources/june has to DECLARE the type.
    `varargs[untyped]` on a macro and the `T` of a generic are not types a test
    could name; `int`, `string` and `cstring` are Nim's own, and asking a test
    to "name int" is a word search that cannot fail. Declared-in-sources
    separates a real receiver from all of those and needs no list to keep up to
    date.
    """
    declared = declared_types()
    receivers = {}
    for name in hand_written:
        path = os.path.join("sources", "june", name)
        if not os.path.exists(path):
            continue
        with open(path) as handle:
            for line in handle:
                match = receiver.match(line)
                if match and match.group(2) in declared:
                    receivers.setdefault(match.group(2), set()).add(match.group(1))

    used = ""
    for pattern in ("tests/test_juce_*.nim", "examples/*.nim"):
        for path in glob.glob(pattern):
            with open(path) as handle:
                used += handle.read()

    unnamed = sorted(t for t in receivers
                     if t not in unnameable_receivers
                     and not re.search(r"\b" + t + r"\b", used)
                     and not re.search(r"\bmake" + t + r"\b", used))
    stale = sorted(t for t in unnameable_receivers if t not in receivers)

    if unnamed:
        print("No test names these types, so nothing calls the bindings "
              "declared on them - the name check above is satisfied by "
              "same-named methods on other types:", file=sys.stderr)
        for name in unnamed:
            print(f"  {name}  ({len(receivers[name])} bindings)", file=sys.stderr)
    if stale:
        print("These are listed as unnameable receivers but no longer have "
              "bindings:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
    if not (unnamed or stale):
        print(f"all {len(receivers)} receiver types carrying a hand-written "
              f"binding are named by a test")
    return not (unnamed or stale)


def check_licence_headers():
    """Every file under sources/ carries the project's copyright notice, once.

    A generated file is still a file in this repository. When the generator's
    prolog omits the notice, regenerating silently removes the line naming the
    project's authors - and the result would be offered upstream with the
    upstream author's own copyright stripped out of it.

    A GENERATED file is compared byte for byte against a hand-written one,
    because the notice contains a NON-BREAKING SPACE after the first two
    hashes. A normal space there reads identically and would leave the
    generated modules subtly different from everything around them.

    A HAND-WRITTEN file only has to carry the notice. Two of them - june_stl
    and june_juce_types - spell it with an ordinary space, and that is how the
    project's authors wrote them; normalising their bytes is not this check's
    business. What is checked everywhere is that the notice appears exactly
    ONCE, because a generator that prepends it to a file that already carries
    one produces a doubled header, and a check reading only the first six lines
    cannot see that.
    """
    reference = pathlib.Path("sources/june/juce_core_lifting.nim")
    expected = "\n".join(reference.read_text(encoding="utf-8").split("\n")[:6])
    marker = "June - Copyright (c)"
    modules = ("juce_core", "juce_events", "juce_data_structures",
               "juce_graphics", "juce_gui_basics")
    generated = {f"{m}.nim" for m in modules}
    generated |= {f"{m}_subclasses.nim" for m in modules}

    wrong, absent, doubled = [], [], []
    for path in sorted(pathlib.Path("sources").rglob("*.nim")):
        text = path.read_text(encoding="utf-8")
        head = "\n".join(text.split("\n")[:6])
        is_generated = path.name in generated
        if marker not in head:
            absent.append(path)
        elif is_generated and head != expected:
            wrong.append(path)
        elif text.count(marker) != 1:
            doubled.append((path, text.count(marker)))

    for path in absent:
        print(f"{path} does not open with the project's copyright notice",
              file=sys.stderr)
    for path in wrong:
        print(f"{path} is generated, so its notice must match "
              f"{reference} byte for byte (note the non-breaking space)",
              file=sys.stderr)
    for path, count in doubled:
        print(f"{path} carries the copyright notice {count} times",
              file=sys.stderr)
    return not (absent or wrong or doubled)


def check_operators(declared, lines_by_name, used):
    """Every exported operator, against the way operator_uses says it is checked.

    Returns the messages that make this fail. Three ways to fail, and each is
    read off the tree rather than trusted: an entry naming an operator that no
    longer exists, an operator with no entry, and an entry whose fragment is no
    longer in the tests.
    """
    problems = []
    operators = {name for name in declared if not name.isidentifier()}

    for name in sorted(operator_uses):
        if name not in operators:
            problems.append(
                f"`{name}` is listed in operator_uses but is no longer an "
                f"exported operator")

    for name in sorted(operators):
        if name not in operator_uses:
            problems.append(
                f"`{name}` is exported but operator_uses does not say how it "
                f"is checked. An operator is applied as syntax, so the "
                f"by-name search cannot find its call sites: add the fragment "
                f"of the tests that applies it.")
            continue

        kind, fragment = operator_uses[name]
        if kind == APPLIED:
            if fragment not in used:
                problems.append(
                    f"`{name}` is recorded as applied by  {fragment}  and "
                    f"that is no longer in the tests or examples")
        else:
            bound = [line.strip() for line in lines_by_name[name]
                     if "importcpp" in line]
            if bound:
                problems.append(
                    f"`{name}` is recorded as having no C++ binding behind "
                    f"it, but one of its declarations now has an importcpp:\n"
                    f"    {bound[0]}")
    return problems


def main():
    declared = {}
    declarations = []
    lines_by_name = {}
    for name in hand_written:
        path = os.path.join("sources", "june", name)
        if not os.path.exists(path):
            continue
        with open(path) as handle:
            for line in handle:
                match = export.match(line)
                if match:
                    routine = match.group(1).strip("`")
                    declared.setdefault(routine, name)
                    # Kept alongside, because setdefault throws the second
                    # and later files away: `items` is declared in five of
                    # these and `release` in two. The check is by NAME on
                    # purpose, but the figure printed at the end must not
                    # read as a count of declarations when it is a count of
                    # names.
                    declarations.append((routine, name))
                    lines_by_name.setdefault(routine, []).append(line)

    used = test_sources(count_harness=False)

    # Operators are held to operator_uses instead: `\b==\b` matches nothing,
    # and a name-shaped search for one would answer a question nobody asked.
    by_name = {name for name in declared if name.isidentifier()}

    # Which files each name is declared in, derived from the list above so
    # there is one accumulation rather than two that can fall out of step.
    declared_in = {}
    for declared_name, declared_file in declarations:
        declared_in.setdefault(declared_name, []).append(declared_file)

    uncovered = sorted(
        name for name in by_name
        if name not in uncallable
        and not re.search(r"\b" + re.escape(name) + r"\b", used))

    stale = sorted(name for name in uncallable if name not in declared)

    operator_problems = check_operators(declared, lines_by_name, used)
    called_ok = check_names_are_called_not_mentioned(declared)

    # An exemption that covers more than one declaration is excusing something
    # its reason never mentioned.
    ambiguous = sorted(name for name in uncallable
                       if len(set(declared_in.get(name, []))) > 1)
    if ambiguous:
        print("These `uncallable` entries name more than one declaration, so "
              "the reason recorded for one of them excuses the others too:",
              file=sys.stderr)
        for name in ambiguous:
            where = ", ".join(sorted(set(declared_in[name])))
            print(f"  {name}  (declared in {where})", file=sys.stderr)

    if stale:
        print("These are listed as uncallable but no longer exist:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)

    if uncovered:
        print(f"{len(uncovered)} hand-written binding(s) are never called, so "
              f"nothing compiles their importcpp:", file=sys.stderr)
        for name in uncovered:
            print(f"  {name}  ({declared[name]})", file=sys.stderr)
        print("Call it from a test, or add it to `uncallable` with the reason "
              "a test cannot.", file=sys.stderr)

    for problem in operator_problems:
        print(problem, file=sys.stderr)

    licences_ok = check_licence_headers()
    receivers_ok = check_receiver_types_named()
    gitignore_ok = check_gitignore_order()
    iterators_ok = check_iterator_promises()
    defaults_ok = check_implicit_defaults()
    subclasses_ok = check_subclasses()
    handlers_ok = check_handlers()
    constructors_ok = check_no_argument_constructors()
    constants_ok = check_constants()
    statics_ok = check_static_variables()
    classes_ok = check_classes()
    inherited_ok = check_inherited_methods()
    signatures_ok = check_one_declaration_per_signature()
    literals_ok = check_integer_literal_overloads()
    fields_ok = check_field_accessors()
    macos_ok = check_macos_only_calls()

    if (uncovered or stale or operator_problems or not called_ok or not licences_ok
            or not iterators_ok or not defaults_ok or not subclasses_ok
            or not handlers_ok or not constructors_ok or not constants_ok
            or not statics_ok or not classes_ok or not inherited_ok
            or not signatures_ok or not literals_ok or not fields_ok
            or not gitignore_ok or not macos_ok or ambiguous
            or not receivers_ok):
        sys.exit(1)

    shared = len(declarations) - len(declared)
    operators = len(declared) - len(by_name)
    print(f"all {len(declared)} hand-written binding names are exercised: "
          f"{len(by_name)} found by name in the tests "
          f"({len(uncallable)} of them listed as uncallable), "
          f"{operators} operators held to operator_uses"
          + (f", {shared} declarations share a name with another"
             if shared else ""))


if __name__ == "__main__":
    main()
